<?php
/**
 * One-off exporter: dumps the local, verified-correct content database into a portable
 * PHP array (storage/seed_data.php) that app/Ops/AutoSetup.php replays into a fresh MySQL
 * database on first production request. Used because this deploy has no SSH/remote-MySQL
 * access — see DEPLOY.md and the deploy conversation for why.
 *
 * Tables are listed in FK-safe insert order. Transient/environment tables (sessions,
 * enquiries, events, audit_log, build_jobs) are intentionally excluded — production starts
 * with those empty.
 *
 *   php tools/export_prod_data.php
 */
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';

use Nm\Db; use Nm\Schema;

$tables = [
    'users', 'media', 'media_variant', 'media_i18n', 'categories', 'category_i18n',
    'products', 'product_i18n', 'services', 'service_i18n', 'posts', 'post_i18n',
    'blocks', 'block_i18n', 'faqs', 'faq_i18n', 'settings', 'seo_meta', 'redirects',
];

$data = [];
foreach ($tables as $t) {
    $data[$t] = Db::all("SELECT * FROM \"$t\"");
}

$out = "<?php\n"
     . "/* generated by tools/export_prod_data.php — do not hand-edit */\n"
     . "return " . var_export(['schema' => Schema::ddl('mysql'), 'tables' => $data], true) . ";\n";

$destDir = nm_path('storage');
if (!is_dir($destDir)) mkdir($destDir, 0775, true);
file_put_contents($destDir . '/seed_data.php', $out);

$n = 0; foreach ($data as $rows) $n += count($rows);
echo "exported " . count($tables) . " tables, $n rows -> storage/seed_data.php\n";
