<?php
/**
 * Static rebuild (doc 04 §2 / §9). This is the only thing that writes public_html/**\/*.html.
 *
 *   php tools/rebuild.php full                     rebuild every page in every language
 *   php tools/rebuild.php sitemaps                 sitemaps + robots + 404 only
 *   php tools/rebuild.php page en about            one logical page, all languages
 *   php tools/rebuild.php page en categories/fresh-fruits
 *   php tools/rebuild.php full --purge-cache         drop file caches first
 *   php tools/rebuild.php full --only=ar           one locale (hotfix)
 *
 * Exit codes: 0 ok · 1 render/write failure (nothing partial is ever published: each page is
 * written with tmp+rename, so a crash mid-run leaves the previous HTML intact).
 */
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';

use Nm\Cache;
use Nm\Db;
use Nm\I18n;
use Nm\PublicController;
use Nm\StaticBuilder;
use Nm\View;

$argvv = $argv ?? [];
$args = array_slice($argvv, 1);
if (($args[0] ?? '') === '--') array_shift($args);   // php-wasm CLI separator, see tools/build.sh
$cmd = $args[0] ?? 'full';
$purge = in_array('--purge-cache', $args, true);
$only = null;
foreach ($args as $a) if (str_starts_with($a, '--only=')) $only = substr($a, 7);
$public = rtrim((string) cfg('paths.public'), '/');
if (!is_dir($public)) mkdir($public, 0775, true);

$jobId = 0;
try {
    Db::run('INSERT INTO build_jobs(scope,status,pages) VALUES(?,\'running\',0)', [$cmd]);
    $jobId = Db::lastId();
} catch (\Throwable) { /* table may not exist yet on a virgin box — rebuild still proceeds */ }

$t0 = microtime(true);
$failures = [];
set_error_handler(static function (int $no, string $s, string $f = '', int $l = 0) use (&$failures): bool {
    $failures[] = "$f:$l $s";
    return true;
});

if ($purge || $cmd === 'full') Cache::forgetAll();   /* full builds must never render from a stale cache */
$langs = $only ? [$only] : cfg('langs');

/* per-locale guards, written next to the generated HTML (defense in depth, doc 04 §7) */
foreach ($langs as $l) {
    $d = "$public/$l";
    if (!is_dir($d)) mkdir($d, 0775, true);
    file_put_contents("$d/.htaccess",
        "# generated by tools/rebuild.php — this tree is HTML-only\n"
      . "Options -Indexes -MultiViews\n"
      . "<IfModule mod_rewrite.c>\n  RewriteEngine On\n  RewriteRule \\.php$ - [F,L]\n</IfModule>\n"
      . "<FilesMatch \"\\.html$\">\n  Header always set Cache-Control \"public, max-age=0, must-revalidate, s-maxage=3600, stale-while-revalidate=86400\" enc=br\n</FilesMatch>\n");
}

$n = 0;
try {
    switch ($cmd) {
        case 'full':
            foreach ($langs as $l) {
                foreach (StaticBuilder::pageSpecs($l) as [$path, $page]) {
                    $r = StaticBuilder::writePage($l, $path, $page);
                    if (!$r['skipped']) $n++;
                    if ($n % 100 === 0) fwrite(STDOUT, "  … $n pages\n");
                }
            }
            break;
        case 'page':
            $path = (string) ($args[2] ?? '');
            foreach ($langs as $l) { StaticBuilder::writePage($l, $path); $n++; }
            break;
        case 'sitemaps':
            StaticBuilder::sitemaps();
            break;
        default:
            fwrite(STDERR, "usage: php tools/rebuild.php full|sitemaps|page <lang> [path] [--purge-cache] [--only=xx]\n");
            exit(1);
    }
    StaticBuilder::sitemaps();
    StaticBuilder::robots();
    /* ErrorDocument 404 target (default locale; it self-links by absolute path) */
    I18n::boot(cfg('default_lang'));
    $nf = PublicController::notFound(cfg('default_lang'), '');
    file_put_contents("$public/404.html", $nf['html']);
} catch (\Throwable $e) {
    $failures[] = (string) $e;
}

restore_error_handler();
$ms = (int) round((microtime(true) - $t0) * 1000);
$ok = !$failures;
try {
    $sql = $jobId ? 'UPDATE build_jobs SET status=?, pages=?, ms=?, error=?, finished_at=? WHERE id=?' : '';
    if ($jobId) Db::run($sql, [$ok ? 'done' : 'failed', $n, $ms, $ok ? null : mb_substr(implode("\n", $failures), 0, 4000), date('Y-m-d H:i:s'), $jobId]);
} catch (\Throwable) { }

if (!$ok) {
    fwrite(STDERR, "REBUILD FAILED (" . count($failures) . " problems):\n");
    foreach (array_slice($failures, 0, 12) as $f) fwrite(STDERR, "  - $f\n");
    exit(1);
}
printf("rebuilt %d pages in %d ms → %s\n", $n, $ms, $public);
