<?php
/** Services, FAQs, zone blocks, blog posts — EN/AR/FR. `$L` accepts strings or string lists (bullets). */
$L = static fn(mixed $en, mixed $ar, mixed $fr) => ['en' => $en, 'ar' => $ar, 'fr' => $fr];

$services = [
 ['code' => 'sourcing-selection', 'icon' => 'search',
  'name' => $L('Sourcing & Selection', 'التوريد والانتقاء', 'Sourcing & sélection'),
  'teaser' => $L('Careful farm selection and pre-shipment quality sorting.', 'انتقاء مزارع دقيق وفرز جودة قبل الشحن.', 'Sélection soignée des fermes et tri qualité avant expédition.'),
  'body' => $L(
   "Every programme starts at the farm. We assess growing areas, harvest calendars and field performance, then sort the received crop by grade, colour, size and defect level.\n\nNothing is shipped because it *can* be shipped. Products move forward only when the variety, maturity, firmness and visual quality meet the buyer's specification and the destination market's expectations.\n\nSelection also protects commercial performance: the right variety, at the right maturity, in the right pack, is what reduces rejects at arrival.",
   "تبدأ كل عملية من المزرعة. نُقيّم مناطق الزراعة وتقويمات الحصاد وأداء الحقول، ثم نفرز المحصول المستلم حسب الدرجة واللون والحجم ونسبة العيوب.\n\nلا يُشحن شيء لمجرد أنه *يمكن* شحنه. تتقدم المنتجات فقط عندما تتوافق الصنف والنضج والصلابة والجودة الظاهرية مع مواصفة المشتري وتوقعات سوق الوجهة.\n\nالانتقاء يحمي الأداء التجاري أيضًا: الصنف الصحيح في النضج الصحيح والعبوة الصحيحة هو ما يقلل الرفض عند الوصول.",
   "Chaque programme commence à la ferme. Nous évaluons zones de culture, calendriers de récolte et performance au champ, puis trions la réception par grade, couleur, calibre et défauts.\n\nRien n'est expédié simplement parce que c'est *possible*. Les produits avancent quand la variété, la maturité, la fermeté et la qualité visuelle respectent la spécification de l'acheteur et les attentes du marché.\n\nLa sélection protège aussi la performance commerciale : la bonne variété, à la bonne maturité, dans le bon emballage, réduit les refus à l'arrivée."),
  'bullets' => $L(['Farm assessment', 'Grade sorting', 'Colour & size calibration', 'Defect screening'],
   ['تقييم المزارع', 'فرز الدرجات', 'معايرة اللون والحجم', 'فحص العيوب'],
   ['Évaluation des fermes', 'Tri par grades', 'Calibrage couleur/taille', 'Détection des défauts'])],
 ['code' => 'export-handling', 'icon' => 'truck',
  'name' => $L('Export Handling', 'التداول التصديري', 'Manutention export'),
  'teaser' => $L('Post-harvest care, cooling and transport-ready packing.', 'رعاية ما بعد الحصاد وتبريد وتعبئة جاهزة للنقل.', 'Soins post-récolte, refroidissement et emballage prêt au transport.'),
  'body' => $L(
   "Post-harvest care protects everything invested in the field. We remove field heat quickly, wash or clean according to product type, then pack for transport rather than display.\n\nVentilation, cushioning, stacking strength and pallet stability are specified per product so containers arrive in the condition they left.\n\nFresh, frozen and shelf-stable lines each follow their own handling protocol — but one rule applies to all: the chain is never broken.",
   "تحمي رعاية ما بعد الحصاد كل ما استُثمر في الحقل. نُزيل حرارة الحقل سريعًا، ونغسل أو ننظف حسب نوع المنتج، ثم نُعبأ للنقل لا للعرض.\n\nتُحدد التهوية والحماية وقوة الرص وثبات الطبلات لكل منتج لتصل الحاويات بالحالة التي خرجت بها.\n\nلكل خط طازج أو مجمد أو طويل الحفظ بروتوكول تداول خاص — وقاعدة واحدة تنطبق على الجميع: السلسلة لا تنقطع أبدًا.",
   "Les soins post-récolte protègent tout l'investissement du champ. Nous évacuons la chaleur rapidement, lavons ou nettoyons selon le produit, puis emballons pour le transport plutôt que pour la vitrine.\n\nVentilation, calage, résistance au gerbage et stabilité palette sont spécifiés produit par produit pour que les conteneurs arrivent tels que partis.\n\nFrais, surgelé et longue conservation suivent chacun leur protocole — une règle pour tous : la chaîne ne se rompt jamais."),
  'bullets' => $L(['Rapid cooling', 'Transport-grade packing', 'Pallet stability', 'Unbroken cold chain'],
   ['تبريد سريع', 'تعبئة بمستوى النقل', 'ثبات الطبلات', 'سلسلة تبريد غير منقطعة'],
   ['Refroidissement rapide', 'Emballage transport', 'Stabilité palette', 'Chaîne du froid continue'])],
 ['code' => 'processing-freezing', 'icon' => 'factory',
  'name' => $L('Processing & Freezing', 'التصنيع والتجميد', 'Transformation & surgélation'),
  'teaser' => $L('IQF freezing and shelf-stable processing to agreed recipes.', 'تجميد IQF وتصنيع طويل الحفظ وفق وصفات متفق عليها.', 'Surgélation IQF et transformation longue conservation selon recette.'),
  'body' => $L(
   "Freezing preserves the season. Vegetables and fruits are washed, cut, graded and individually quick-frozen so grains stay separate and texture survives storage.\n\nShelf-stable lines are prepared to agreed recipes with controlled fill weights, thermal processing, sealing and documented shelf life.\n\nBuyer-specific blends, cuts and pack formats are produced on request — specification first, production second.",
   "التجميد يحفظ الموسم. تُغسل الخضروات والفواكه وتُقطع وتُدرج وتُجمد فرديًا بسرعة لتبقى الحبات منفصلة ويصمد القوام خلال التخزين.\n\nتُجهز خطوط الحفظ الطويل وفق وصفات متفق عليها بأوزان تعبئة مضبوطة ومعالجة حرارية وإغلاق ومدة صلاحية موثقة.\n\nتُنتج الخلطات والقطوعات وصيغ التعبئة الخاصة بالمشتري عند الطلب — المواصفة أولًا ثم الإنتاج.",
   "La surgélation préserve la saison. Légumes et fruits sont lavés, coupés, calibrés et surgelés individuellement : grains séparés, texture préservée au stockage.\n\nLes lignes longue conservation suivent recette convenue, poids net maîtrisé, traitement thermique, sertissage et DLUO documentée.\n\nBlends, coupes et formats spécifiques acheteurs sont produits sur demande — la spécification d'abord, la production ensuite."),
  'bullets' => $L(['IQF individual freezing', 'Recipe-controlled processing', 'Fill-weight accuracy', 'Custom blends & cuts'],
   ['تجميد فردي IQF', 'تصنيع مضبوط الوصفة', 'دقة أوزان التعبئة', 'خلطات وقطوعات مخصصة'],
   ['Surgélation IQF', 'Transformation sur recette', 'Précision du poids net', 'Blends et coupes sur mesure'])],
 ['code' => 'packaging-labelling', 'icon' => 'box',
  'name' => $L('Packaging & Labelling', 'التعبئة والبطاقة', 'Emballage & étiquetage'),
  'teaser' => $L('Retail, food-service and private-label pack formats.', 'صيغ تعبئة للتجزئة والقطاع الغذائي والعلامات الخاصة.', 'Formats détail, food-service et marque distributeur.'),
  'body' => $L(
   "Packaging is a commercial decision as much as a protective one. We supply retail packs, food-service formats, bulk options and private-label presentation.\n\nLabelling follows destination requirements: product identity, net weight, ingredients where applicable, origin, lot and date coding.\n\nArtwork, language versions and regulatory marks are confirmed with the buyer before production runs.",
   "التعبئة قرار تجاري بقدر ما هي قرار وقائي. نوفر عبوات التجزئة وصيغ القطاع الغذائي والخيارات السائبة وعروض العلامات الخاصة.\n\nتتبع البطاقة متطلبات الوجهة: هوية المنتج والوزن الصافي والمكونات عند الاقتضاء والمنشأ والدفعة وترميز التاريخ.\n\nتُؤكد الأعمال الفنية ونسخ اللغات والعلامات التنظيمية مع المشتري قبل بدء الإنتاج.",
   "L'emballage est une décision commerciale autant que protectrice : packs détail, formats food-service, vrac et présentation marque distributeur.\n\nL'étiquetage suit les exigences de destination : identité produit, poids net, ingrédients le cas échéant, origine, lot et codage date.\n\nMaquettes, versions linguistiques et marques réglementaires sont validées avec l'acheteur avant production."),
  'bullets' => $L(['Retail & food-service formats', 'Private label', 'Destination-compliant labels', 'Artwork confirmation'],
   ['صيغ تجزئة وقطاع غذائي', 'علامة خاصة', 'بطاقات مطابقة للوجهة', 'تأكيد الأعمال الفنية'],
   ['Formats détail & food-service', 'Marque distributeur', 'Étiquettes conformes', 'Validation des maquettes'])],
 ['code' => 'cold-chain-logistics', 'icon' => 'globe',
  'name' => $L('Cold-Chain & Logistics', 'سلسلة التبريد واللوجستيات', 'Chaîne du froid & logistique'),
  'teaser' => $L('Temperature discipline from packhouse to destination.', 'انضباط حراري من بيت التعبئة إلى الوجهة.', 'Discipline thermique du station de conditionnement à destination.'),
  'body' => $L(
   "Temperature discipline is planned before the first pallet moves: pre-cooling, set points, ventilation patterns and maximum transit windows per product.\n\nDocumentation travels with the load — packing lists, phytosanitary or health certificates where required, certificates of origin, invoices and transport records.\n\nWe coordinate container booking, loading supervision and arrival follow-up so questions have answers while the shipment is still moving.",
   "يُخطط الانضباط الحراري قبل تحرك أول طبلة: تبريد مسبق ونقاط ضبط وأنماط تهوية وأقصى فترات عبور لكل منتج.\n\nترافق المستندات الشحنة — قوائم التعبئة والشهادات الصحية أو النباتية عند الحاجة وشهادات المنشأ والفواتير وسجلات النقل.\n\nننسق حجز الحاويات والإشراف على التحميل ومتابعة الوصول لتبقى للأسئلة إجابات والشحنة في طريقها.",
   "La discipline thermique est planifiée avant la première palette : pré-refroidissement, consignes, ventilation et fenêtres de transit maximales par produit.\n\nLes documents voyagent avec la charge — listes de colisage, certificats sanitaires ou phytosanitaires, certificats d'origine, factures et relevés de transport.\n\nNous coordonnons réservation, supervision du chargement et suivi à l'arrivée."),
  'bullets' => $L(['Pre-cooling & set points', 'Transit-window planning', 'Full documentation', 'Arrival follow-up'],
   ['تبريد مسبق ونقاط ضبط', 'تخطيط فترات العبور', 'توثيق كامل', 'متابعة عند الوصول'],
   ['Pré-refroidissement', 'Planification du transit', 'Documentation complète', 'Suivi à l’arrivée'])],
 ['code' => 'buyers-support', 'icon' => 'chat',
  'name' => $L('Buyer Support', 'دعم المشترين', 'Support acheteurs'),
  'teaser' => $L('Specifications, samples, quotations and after-shipment follow-up.', 'مواصفات وعينات وعروض أسعار ومتابعة بعد الشحن.', 'Spécifications, échantillons, devis et suivi post-expédition.'),
  'body' => $L(
   "Importers, distributors, processors and retailers get a single point of contact for specification discussions, samples, availability windows and quotations.\n\nWe answer what buyers actually ask: Which varieties are in season now? What pack fits my channel? What documentation will arrive with the load?\n\nAfter shipment, we follow up on arrival condition and keep records that make the next order faster.",
   "يحصل المستوردون والموزعون والمصنعون وتجار التجزئة على نقطة اتصال واحدة لمناقشة المواصفات والعينات وفترات التوافر وعروض الأسعار.\n\nنجيب على ما يسأله المشترون فعلًا: أي الأصناف في الموسم الآن؟ أي عبوة تناسب قناتي؟ ما المستندات التي ستصل مع الشحنة؟\n\nبعد الشحن نتابع حالة الوصول ونحتفظ بسجلات تجعل الطلب التالي أسرع.",
   "Importateurs, distributeurs, industriels et détaillants disposent d'un interlocuteur unique pour spécifications, échantillons, fenêtres de disponibilité et devis.\n\nNous répondons aux vraies questions : quelles variétés sont en saison ? quel emballage pour mon canal ? quels documents accompagnent la charge ?\n\nAprès expédition, nous suivons l'état à l'arrivée et archivons pour accélérer la commande suivante."),
  'bullets' => $L(['Single point of contact', 'Samples & specifications', 'Seasonal availability advice', 'Post-arrival follow-up'],
   ['نقطة اتصال واحدة', 'عينات ومواصفات', 'استشارة التوافر الموسمي', 'متابعة بعد الوصول'],
   ['Interlocuteur unique', 'Échantillons & spécifications', 'Conseil saisonnier', 'Suivi post-arrivée'])],
];

$faqs = [
 ['group' => 'export', 'q' => $L('Which products does Nile-Maple supply?', 'ما المنتجات التي توردها نيل مابل؟', 'Quels produits Nile-Maple fournit-elle ?'),
  'a' => $L('Four divisions: fresh fruits (31 lines), fresh vegetables (37), IQF frozen products (36) and manufactured/processed/canned foods (55) — 159 export product lines in total.',
    'أربعة قطاعات: فواكه طازجة (31 خطًا)، خضروات طازجة (37)، منتجات مجمدة IQF (36)، وأغذية مصنعة ومعلبة (55) — بإجمالي 159 خط تصدير.',
    'Quatre divisions : fruits frais (31), légumes frais (37), surgelés IQF (36) et produits transformés/appertisés (55) — 159 références export.')],
 ['group' => 'export', 'q' => $L('Where do you export?', 'إلى أين تصدرون؟', 'Où exportez-vous ?'),
  'a' => $L('We serve importers, distributors, processors and retailers across the Middle East, Europe and Africa, with documentation prepared per destination market.',
    'نخدم المستوردين والموزعين والمصنعين وتجار التجزئة في الشرق الأوسط وأوروبا وأفريقيا، مع تجهيز المستندات حسب سوق الوجهة.',
    'Nous servons importateurs, distributeurs, industriels et détaillants au Moyen-Orient, en Europe et en Afrique, avec documentation adaptée à chaque destination.')],
 ['group' => 'export', 'q' => $L('How quickly can I receive a quotation?', 'كم تستغرق عروض الأسعار؟', 'Sous quel délai recevrai-je un devis ?'),
  'a' => $L('Send the product, quantity, destination and pack preference and we reply within one working day with availability, specification and price terms.',
    'أرسل المنتج والكمية والوجهة وتفضيل التعبئة ونرد خلال يوم عمل واحد بالتوافر والمواصفة وشروط السعر.',
    'Envoyez produit, quantité, destination et emballage souhaité : réponse sous un jour ouvré avec disponibilité, spécification et conditions de prix.')],
 ['group' => 'quality', 'q' => $L('What quality checks are applied before shipment?', 'ما فحوصات الجودة المطبقة قبل الشحن؟', 'Quels contrôles qualité avant expédition ?'),
  'a' => $L('Incoming inspection, grade sorting by colour/size/defects, product-specific preparation, packing protection verification, and temperature control from cooling to loading.',
    'فحص الاستلام، فرز الدرجات حسب اللون والحجم والعيوب، تجهيز خاص بكل منتج، التحقق من حماية التعبئة، وضبط الحرارة من التبريد حتى التحميل.',
    'Inspection à réception, tri par grade (couleur/taille/défauts), préparation spécifique produit, vérification de la protection d’emballage et contrôle température jusqu’au chargement.')],
 ['group' => 'quality', 'q' => $L('How is the cold chain managed?', 'كيف تُدار سلسلة التبريد؟', 'Comment la chaîne du froid est-elle gérée ?'),
  'a' => $L('Pre-cooling removes field heat quickly, set temperatures follow each product\'s guide, ventilation and stacking are specified per pack, and frozen goods hold −18 °C storage with an unbroken frozen chain to destination.',
    'يزيل التبريد المسبق حرارة الحقل سريعًا، وتُضبط الحرارة وفق دليل كل منتج، وتُحدد التهوية والرص لكل عبوة، وتُحفظ المجمدات عند −18 °م بسلسلة تجميد غير منقطعة حتى الوجهة.',
    'Le pré-refroidissement évacue la chaleur, les consignes suivent le guide produit, ventilation et gerbage sont spécifiés, et les surgelés restent à −18 °C avec chaîne ininterrompue jusqu’à destination.')],
 ['group' => 'quality', 'q' => $L('Can you produce to my specification?', 'هل تنتجون وفق مواصفتي؟', 'Pouvez-vous produire selon ma spécification ?'),
  'a' => $L('Yes — cuts, blends, pack formats and private-label presentation are confirmed against your written specification before production runs.',
    'نعم — القطوعات والخلطات وصيغ التعبئة وعروض العلامة الخاصة تُؤكد مقابل مواصفتك المكتوبة قبل بدء الإنتاج.',
    'Oui — coupes, blends, formats et présentation MDD sont validés contre votre spécification écrite avant production.')],
 ['group' => 'logistics', 'q' => $L('What documentation accompanies shipments?', 'ما المستندات المرافقة للشحنات؟', 'Quels documents accompagnent les expéditions ?'),
  'a' => $L('Packing lists, commercial invoices, certificates of origin, phytosanitary or health certificates where required, plus labelling that meets the destination market.',
    'قوائم التعبئة والفواتير التجارية وشهادات المنشأ والشهادات النباتية أو الصحية عند الحاجة، إضافة إلى بطاقة مطابقة لسوق الوجهة.',
    'Listes de colisage, factures commerciales, certificats d’origine, certificats phytosanitaires ou sanitaires si requis, et étiquetage conforme à la destination.')],
 ['group' => 'logistics', 'q' => $L('Which pack formats are available?', 'ما صيغ التعبئة المتاحة؟', 'Quels formats d’emballage proposez-vous ?'),
  'a' => $L('Ventilated and telescopic cartons, mesh bags, punnets and clamshells for fresh; retail cans, glass jars, pouches, drums and bulk for processed; and IQF cartons sized to the channel.',
    'كراتين مهواة وتلسكوبية وأكياس شبكية وعبونات صغيرة وصدفية للطازج؛ عبوات معدنية وبرطمانات زجاجية وأكياس وبراميل وسائب للمصنع؛ وكراتين IQF بحجم القناة.',
    'Cartons ventilés et télescopiques, filets, barquettes pour le frais ; boîtes métal, bocaux, sachets, fûts et vrac pour le transformé ; cartons IQF adaptés au canal.')],
 ['group' => 'seasonal', 'q' => $L('What is in season now?', 'ما المتاح في الموسم الآن؟', 'Qu’est-ce qui est en saison ?'),
  'a' => $L('Check the Seasonal Availability page for current windows across the year, then request a live availability confirmation for your volume and destination.',
    'راجع صفحة التوافر الموسمي للاطلاع على الفترات الحالية عبر العام، ثم اطلب تأكيد توافر فعليًا لكميتك ووجهتك.',
    'Consultez la page Disponibilité saisonnière pour les fenêtres actuelles, puis demandez une confirmation de disponibilité pour votre volume et destination.')],
 ['group' => 'seasonal', 'q' => $L('Can frozen products supply outside the fresh season?', 'هل تغطي المنتجات المجمدة خارج موسم الطازج؟', 'Le surgelé couvre-t-il hors saison du frais ?'),
  'a' => $L('Yes. IQF freezing preserves the harvest so vegetables and fruits remain available year-round while fresh windows are closed.',
    'نعم. يحفظ تجميد IQF المحصول فتبقى الخضروات والفواكه متاحة طوال العام بينما تكون فترات الطازج مغلقة.',
    'Oui. La surgélation IQF préserve la récolte : légumes et fruits restent disponibles toute l’année hors fenêtres du frais.')],
 ['group' => 'company', 'q' => $L('Who owns the company?', 'من يملك الشركة؟', 'Qui détient l’entreprise ?'),
  'a' => $L('Eng. Omar Issa (Founder & CEO) with Eng. Yasser Yehia as Executive Advisor and Eng. Ahmed Abouelenein as Board Member & Financial Advisor.',
    'المهندس عمر عيسى (المؤسس والرئيس التنفيذي) مع المهندس ياسر يحيى مستشارًا تنفيذيًا والمهندس أحمد أبو العنين عضو مجلس إدارة ومستشارًا ماليًا.',
    'Eng. Omar Issa (Fondateur & CEO), avec Eng. Yasser Yehia comme Conseiller exécutif et Eng. Ahmed Abouelenein, Administrateur & Conseiller financier.')],
 ['group' => 'company', 'q' => $L('How do I place an order?', 'كيف أطلب؟', 'Comment passer commande ?'),
  'a' => $L('Use the contact form, email sales@nilemaple.com or message us on WhatsApp with product, specification, quantity, destination and required delivery window.',
    'استخدم نموذج الاتصال أو راسل sales@nilemaple.com أو تواصل عبر واتساب مع ذكر المنتج والمواصفة والكمية والوجهة وفترة التسليم المطلوبة.',
    'Utilisez le formulaire, écrivez à sales@nilemaple.com ou contactez-nous sur WhatsApp avec produit, spécification, quantité, destination et fenêtre de livraison.')],
];

$media = static fn(string $ref) => ['__ref' => $ref];   // resolved to media ids during seed

$blocks = [
 /* ---------------- home ---------------- */
 ['zone' => 'home:hero', 'kind' => 'hero', 'base' => ['media' => 'profile/image3.jpg', 'lead' => null],
  'title' => $L('Egyptian Agricultural Products, Handled with Care', 'منتجات زراعية مصرية بتداول حريص', 'Produits agricoles égyptiens, manipulés avec soin'),
  'eyebrow' => $L('Nile-Maple · Agriculture Export', 'نيل مابل · تصدير زراعي', 'Nile-Maple · Export agricole'),
  'payload' => $L(['lead' => 'From field to destination, we focus on careful handling, quality sorting, temperature control, reliable export packing and professional communication.'],
                  ['lead' => 'من الحقل إلى الوجهة، نركز على التداول الحريص وفرز الجودة وضبط الحرارة وتعبئة تصدير موثوقة وتواصل احترافي.'],
                  ['lead' => 'Du champ à destination : manutention soignée, tri qualité, contrôle de température, emballage export fiable et communication professionnelle.'])],
 ['zone' => 'home:stats', 'kind' => 'stat', 'base' => ['items' => [
   ['value' => 4, 'label' => 'Operating divisions'], ['value' => 159, 'label' => 'Product lines'],
   ['value' => 3, 'label' => 'Languages served'], ['value' => 48, 'label' => 'Hour quote response', 'suffix' => 'h']]],
  'title' => null, 'eyebrow' => null,
  'payload' => $L(['items' => [['value' => 4, 'label' => 'قطاعات تشغيلية'], ['value' => 159, 'label' => 'خط منتج'], ['value' => 3, 'label' => 'لغات خدمة'], ['value' => 48, 'label' => 'ساعة للرد على عرض السعر', 'suffix' => 'س']]],
                  ['items' => [['value' => 4, 'label' => 'Divisions opérationnelles'], ['value' => 159, 'label' => 'Références produit'], ['value' => 3, 'label' => 'Langues servies'], ['value' => 48, 'label' => 'Heures de réponse devis', 'suffix' => 'h']]],
                  ['items' => [['value' => 4, 'label' => 'قطاعات تشغيلية'], ['value' => 159, 'label' => 'خط منتج'], ['value' => 3, 'label' => 'لغات خدمة'], ['value' => 48, 'label' => 'ساعة للرد', 'suffix' => 'س']]])],
 ['zone' => 'home:process', 'kind' => 'list', 'base' => [], 'title' => null, 'eyebrow' => null,
  'payload' => $L(['text' => 'Selection, sorting and grading'], ['text' => 'التوريد والانتقاء'], ['text' => 'Sélection, tri et calibrage']),
 ],
];
/* process steps as 6 separate blocks */
$steps = $L(
 [['t' => 'Sourcing & Selection', 'x' => 'Careful farm selection and pre-shipment sorting.'],
  ['t' => 'Processing & Preparation', 'x' => 'Washing, cutting, grading and product-specific preparation.'],
  ['t' => 'Quality Control', 'x' => 'Specification checks at every stage before approval.'],
  ['t' => 'Packing & Labelling', 'x' => 'Retail, food-service and private-label formats.'],
  ['t' => 'Cold-Chain & Logistics', 'x' => 'Temperature discipline and export documentation.'],
  ['t' => 'Buyer Support', 'x' => 'Samples, quotations and after-shipment follow-up.']],
 [['t' => 'التوريد والانتقاء', 'x' => 'انتقاء مزارع دقيق وفرز قبل الشحن.'],
  ['t' => 'التصنيع والتجهيز', 'x' => 'غسيل وقطع وتدريج وتجهيز خاص بكل منتج.'],
  ['t' => 'ضبط الجودة', 'x' => 'فحوصات مواصفة في كل مرحلة قبل الاعتماد.'],
  ['t' => 'التعبئة والبطاقة', 'x' => 'صيغ تجزئة وقطاع غذائي وعلامة خاصة.'],
  ['t' => 'سلسلة التبريد واللوجستيات', 'x' => 'انضباط حراري ومستندات تصدير.'],
  ['t' => 'دعم المشترين', 'x' => 'عينات وعروض أسعار ومتابعة بعد الشحن.']],
 [['t' => 'Sourcing & sélection', 'x' => 'Sélection soignée des fermes et tri avant expédition.'],
  ['t' => 'Transformation & préparation', 'x' => 'Lavage, coupe, calibrage et préparation spécifique.'],
  ['t' => 'Contrôle qualité', 'x' => 'Vérifications de spécification à chaque étape.'],
  ['t' => 'Emballage & étiquetage', 'x' => 'Formats détail, food-service et MDD.'],
  ['t' => 'Chaîne du froid & logistique', 'x' => 'Discipline thermique et documentation export.'],
  ['t' => 'Support acheteurs', 'x' => 'Échantillons, devis et suivi post-expédition.']]);
$blocks[2] = ['zone' => 'home:process', 'kind' => 'list', 'base' => [], 'title' => null, 'eyebrow' => null, 'payload' => $L(['steps' => $steps['en']], ['steps' => $steps['ar']], ['steps' => $steps['fr']])];

$why = $L(
 [['t' => 'Selection over volume', 'x' => 'Products move only when variety, maturity, firmness and visual quality meet specification.'],
  ['t' => 'Temperature discipline', 'x' => 'From pre-cooling to loading, the chain follows product-specific guides.'],
  ['t' => 'Transport-grade packing', 'x' => 'Ventilation, cushioning and stacking strength specified per product.'],
  ['t' => 'Documentation that travels', 'x' => 'Certificates, packing lists and labels prepared per destination.']],
 [['t' => 'الانتقاء قبل الكمية', 'x' => 'تتحرك المنتجات فقط عندما تتوافق الصنف والنضج والصلابة والجودة مع المواصفة.'],
  ['t' => 'انضباط حراري', 'x' => 'من التبريد المسبق إلى التحميل تتبع السلسلة أدلة كل منتج.'],
  ['t' => 'تعبئة بمستوى النقل', 'x' => 'تهوية وحماية وقوة رص محددة لكل منتج.'],
  ['t' => 'مستندات ترافق الشحنة', 'x' => 'شهادات وقوائم تعبئة وبطاقات مجهزة لكل وجهة.']],
 [['t' => 'La sélection avant le volume', 'x' => 'Les produits avancent quand variété, maturité, fermeté et qualité respectent la spécification.'],
  ['t' => 'Discipline thermique', 'x' => 'Du pré-refroidissement au chargement, la chaîne suit les guides produit.'],
  ['t' => 'Emballage transport', 'x' => 'Ventilation, calage et résistance au gerbage spécifiés par produit.'],
  ['t' => 'Documentation voyageuse', 'x' => 'Certificats, colisage et étiquettes préparés par destination.']]);
$blocks[] = ['zone' => 'home:why', 'kind' => 'list', 'base' => ['media' => 'profile/image5.jpg'], 'title' => $L('Why Buyers Choose Nile-Maple', 'لماذا يختار المشترون نيل مابل', 'Pourquoi les acheteurs choisissent Nile-Maple'),
  'eyebrow' => null, 'payload' => $L(['items' => $why['en']], ['items' => $why['ar']], ['items' => $why['fr']])];

$quality = $L(
 [['i' => 'shield', 't' => 'Incoming inspection', 'x' => 'Every lot checked against specification on arrival.'],
  ['i' => 'thermometer', 't' => 'Temperature control', 'x' => 'Set points and transit windows per product guide.'],
  ['i' => 'check', 't' => 'Packing verification', 'x' => 'Protection, ventilation and labelling confirmed before loading.'],
  ['i' => 'clipboard', 't' => 'Document readiness', 'x' => 'Certificates and lists prepared before the container moves.']],
 [['i' => 'shield', 't' => 'فحص الاستلام', 'x' => 'فحص كل دفعة مقابل المواصفة عند الوصول.'],
  ['i' => 'thermometer', 't' => 'ضبط الحرارة', 'x' => 'نقاط ضبط وفترات عبور وفق دليل كل منتج.'],
  ['i' => 'check', 't' => 'التحقق من التعبئة', 'x' => 'تأكيد الحماية والتهوية والبطاقة قبل التحميل.'],
  ['i' => 'clipboard', 't' => 'جاهزية المستندات', 'x' => 'تجهيز الشهادات والقوائم قبل تحرك الحاوية.']],
 [['i' => 'shield', 't' => 'Inspection à réception', 'x' => 'Chaque lot vérifié contre spécification.'],
  ['i' => 'thermometer', 't' => 'Contrôle température', 'x' => 'Consignes et fenêtres de transit par guide produit.'],
  ['i' => 'check', 't' => 'Vérification emballage', 'x' => 'Protection, ventilation et étiquetage confirmés.'],
  ['i' => 'clipboard', 't' => 'Préparation documentaire', 'x' => 'Certificats et listes prêts avant chargement.']]);
$blocks[] = ['zone' => 'home:quality', 'kind' => 'list', 'base' => [], 'title' => $L('Quality Discipline', 'انضباط الجودة', 'Discipline qualité'),
  'eyebrow' => null, 'payload' => $L(['items' => $quality['en']], ['items' => $quality['ar']], ['items' => $quality['fr']])];
$blocks[] = ['zone' => 'home:quality', 'kind' => 'list', 'base' => [], 'title' => null, 'eyebrow' => null,
  'payload' => $L(['media' => 'profile/image2.jpg'], ['media' => 'profile/image2.jpg'], ['media' => 'profile/image2.jpg'])];

/* ---------------- about ---------------- */
$blocks[] = ['zone' => 'about:intro', 'kind' => 'text', 'base' => [], 'title' => $L('About Nile-Maple', 'عن نيل مابل', 'À propos de Nile-Maple'), 'eyebrow' => $L('Agricultural Trade · Import & Export', 'تجارة زراعية · استيراد وتصدير', 'Commerce agricole · Import & export'),
 'payload' => $L(
  ['paragraphs' => ['Nile-Maple is an agricultural trade, import and export company focused on Egyptian fresh fruits, fresh vegetables, frozen products and manufactured, processed and canned foods.', 'The company operates through four connected divisions covering 159 product lines: sourcing and selection, quality and processing discipline, packing and labelling, and cold-chain export coordination.'], 'media' => 'profile/image1.jpg'],
  ['paragraphs' => ['نيل مابل شركة تجارة زراعية واستيراد وتصدير تركز على الفواكه والخضروات الطازجة المصرية والمنتجات المجمدة والأغذية المصنعة والمعلبة.', 'تعمل الشركة عبر أربعة قطاعات مترابطة تغطي 159 خط منتج: التوريد والانتقاء، وانضباط الجودة والتصنيع، والتعبئة والبطاقة، وتنسيق تصدير سلسلة التبريد.'], 'media' => 'profile/image1.jpg'],
  ['paragraphs' => ['Nile-Maple est une société de commerce agricole, import-export, spécialisée dans les fruits frais, légumes frais, surgelés et produits transformés/appertisés égyptiens.', 'Elle opère via quatre divisions connectées couvrant 159 références : sourcing et sélection, discipline qualité/transformation, emballage et étiquetage, coordination export chaîne du froid.'], 'media' => 'profile/image1.jpg'])];
$blocks[] = ['zone' => 'about:purpose', 'kind' => 'list', 'base' => [], 'title' => $L('Purpose & Operating Model', 'الغرض ونموذج التشغيل', 'Objet & modèle opérationnel'), 'eyebrow' => null,
 'payload' => $L(['items' => [['t' => 'Purpose', 'x' => 'Supply reliable agricultural products that meet the specification, quality expectations and documentation requirements of international buyers.']], 'media' => 'profile/image5.jpg'],
                ['items' => [['t' => 'الغرض', 'x' => 'توريد منتجات زراعية موثوقة تلبي مواصفة وتوقعات جودة ومتطلبات مستندات المشترين الدوليين.']], 'media' => 'profile/image5.jpg'],
                ['items' => [['t' => 'Objet', 'x' => 'Fournir des produits agricoles fiables conformes aux spécifications, attentes qualité et exigences documentaires des acheteurs internationaux.']], 'media' => 'profile/image5.jpg'])];
$blocks[] = ['zone' => 'about:work', 'kind' => 'table', 'base' => [], 'title' => $L('What We Do', 'ما نقوم به', 'Ce que nous faisons'), 'eyebrow' => null,
 'payload' => $L(
  ['cols' => ['Division', 'Scope', 'Focus'], 'rows' => [['Fresh Fruits', '31 lines', 'Harvest maturity and post-harvest handling'], ['Fresh Vegetables', '37 lines', 'Sorting, ventilation and transport condition'], ['Frozen Products', '36 lines', 'Rapid freezing and frozen-chain stability'], ['Processed & Canned', '55 lines', 'Recipe, fill weight, thermal processing and sealing']]],
  ['cols' => ['القطاع', 'النطاق', 'التركيز'], 'rows' => [['فواكه طازجة', '31 خطًا', 'نضج الحصاد ورعاية ما بعده'], ['خضروات طازجة', '37 خطًا', 'فرز وتهوية وحالة نقل'], ['منتجات مجمدة', '36 خطًا', 'تجميد سريع واستقرار سلسلة التجميد'], ['مصنعة ومعلبة', '55 خطًا', 'وصفة ووزن ومعالجة حرارية وإغلاق']]],
  ['cols' => ['Division', 'Périmètre', 'Focus'], 'rows' => [['Fruits frais', '31 réf.', 'Maturité et soins post-récolte'], ['Légumes frais', '37 réf.', 'Tri, ventilation, état transport'], ['Surgelés', '36 réf.', 'Surgélation et stabilité chaîne'], ['Transformés', '55 réf.', 'Recette, poids, traitement, sertissage']]])];
$blocks[] = ['zone' => 'about:export', 'kind' => 'list', 'base' => [], 'title' => $L('Export Coordination', 'تنسيق التصدير', 'Coordination export'), 'eyebrow' => null,
 'payload' => $L(['items' => [['i' => 'box', 't' => 'Packing', 'x' => 'Format and protection matched to product and channel.'], ['i' => 'clipboard', 't' => 'Documentation', 'x' => 'Certificates and lists prepared per destination.'], ['i' => 'truck', 't' => 'Loading', 'x' => 'Supervised stuffing with temperature set points.'], ['i' => 'globe', 't' => 'Arrival', 'x' => 'Follow-up on condition at destination.']], 'media' => 'profile/image3.jpg'],
                ['items' => [['i' => 'box', 't' => 'التعبئة', 'x' => 'صيغة وحماية مطابقتان للمنتج والقناة.'], ['i' => 'clipboard', 't' => 'المستندات', 'x' => 'شهادات وقوائم مجهزة لكل وجهة.'], ['i' => 'truck', 't' => 'التحميل', 'x' => 'إشراف على التحميل مع نقاط ضبط حرارية.'], ['i' => 'globe', 't' => 'الوصول', 'x' => 'متابعة الحالة عند الوجهة.']], 'media' => 'profile/image3.jpg'],
                ['items' => [['i' => 'box', 't' => 'Emballage', 'x' => 'Format et protection selon produit et canal.'], ['i' => 'clipboard', 't' => 'Documentation', 'x' => 'Certificats et listes par destination.'], ['i' => 'truck', 't' => 'Chargement', 'x' => 'Empotage supervisé avec consignes thermiques.'], ['i' => 'globe', 't' => 'Arrivée', 'x' => 'Suivi de l’état à destination.']], 'media' => 'profile/image3.jpg'])];
$blocks[] = ['zone' => 'about:leadership', 'kind' => 'list', 'base' => [], 'title' => $L('Leadership & Governance', 'القيادة والحوكمة', 'Direction & gouvernance'), 'eyebrow' => null,
 'payload' => $L(['people' => [['n' => 'Eng. Omar Issa', 'r' => 'Founder & CEO', 'm' => 'Overall direction and buyer relationships.'], ['n' => 'Eng. Yasser Yehia', 'r' => 'Executive Advisor', 'm' => 'Operational and export advisory.'], ['n' => 'Eng. Ahmed Abouelenein', 'r' => 'Board Member & Financial Advisor', 'm' => 'Governance and financial oversight.']], 'media' => 'profile/image4.jpg'],
                ['people' => [['n' => 'م. عمر عيسى', 'r' => 'المؤسس والرئيس التنفيذي', 'm' => 'التوجيه العام وعلاقات المشترين.'], ['n' => 'م. ياسر يحيى', 'r' => 'مستشار تنفيذي', 'm' => 'استشارات تشغيلية وتصديرية.'], ['n' => 'م. أحمد أبو العنين', 'r' => 'عضو مجلس إدارة ومستشار مالي', 'm' => 'حوكمة وإشراف مالي.']], 'media' => 'profile/image4.jpg'],
                ['people' => [['n' => 'Eng. Omar Issa', 'r' => 'Fondateur & CEO', 'm' => 'Direction générale et relations acheteurs.'], ['n' => 'Eng. Yasser Yehia', 'r' => 'Conseiller exécutif', 'm' => 'Conseil opérationnel et export.'], ['n' => 'Eng. Ahmed Abouelenein', 'r' => 'Administrateur & Conseiller financier', 'm' => 'Gouvernance et supervision financière.']], 'media' => 'profile/image4.jpg'])];
$blocks[] = ['zone' => 'about:vision', 'kind' => 'text', 'base' => [], 'title' => $L('Vision', 'الرؤية', 'Vision'), 'eyebrow' => null,
 'payload' => $L(['paragraphs' => ['To build agricultural trade on consistency: products that match their specification, shipments that arrive in condition, and documentation buyers can rely on.']],
                ['paragraphs' => ['بناء تجارة زراعية على الاتساق: منتجات تطابق مواصفتها، وشحنات تصل بحالة سليمة، ومستندات يعتمد عليها المشترون.']],
                ['paragraphs' => ['Bâtir le commerce agricole sur la constance : des produits conformes à leur spécification, des expéditions qui arrivent en état, et une documentation fiable.']])];

/* ---------------- static pages (markdown, 3 langs) ---------------- */
$pages = [
 'quality-handling' => $L(
  "# Quality & Handling\n\n## Selection\nEvery lot starts with careful farm selection. Produce is inspected at receipt and sorted by grade, colour, size and defect level. Products move forward only when the specification is met — selection protects arrival condition more than any later step.\n\n## Fresh handling\nField heat is removed quickly after harvest. Washing, cleaning, grading and packing follow product-specific protocols. Ventilation, cushioning and stacking strength are specified per pack so containers arrive as they left.\n\n## Frozen handling\nIQF (individually quick frozen) processing keeps grains separate and texture intact. Storage holds −18 °C with an unbroken frozen chain from production to destination.\n\n## Processed handling\nShelf-stable lines follow agreed recipes with controlled fill weights, thermal processing, hermetic sealing and documented shelf life.\n\n## Verification\nPacking protection, labelling accuracy and temperature records are verified before loading. Documentation travels with every shipment.",
  "# الجودة والتداول\n\n## الانتقاء\nتبدأ كل دفعة بانتقاء مزارع دقيق. يُفحص المحصول عند الاستلام ويُفرز حسب الدرجة واللون والحجم ونسبة العيوب. تتقدم المنتجات فقط عند استيفاء المواصفة — فالانتقاء يحمي حالة الوصول أكثر من أي خطوة لاحقة.\n\n## تداول الطازج\nتُزال حرارة الحقل سريعًا بعد الحصاد. يتبع الغسيل والتنظيف والتدريج والتعبئة بروتوكولات خاصة بكل منتج، وتُحدد التهوية والحماية وقوة الرص لكل عبوة.\n\n## تداول المجمد\nيحافظ التجميد الفردي السريع IQF على انفصال الحبات وسلامة القوام، ويُحفظ التخزين عند −18 °م بسلسلة تجميد غير منقطعة حتى الوجهة.\n\n## تداول المصنع\nتتبع خطوط الحفظ الطويل وصفات متفق عليها بأوزان تعبئة مضبوطة ومعالجة حرارية وإغلاق محكم ومدة صلاحية موثقة.\n\n## التحقق\nيُتحقق من حماية التعبئة ودقة البطاقة وسجلات الحرارة قبل التحميل، وترافق المستندات كل شحنة.",
  "# Qualité & manutention\n\n## Sélection\nChaque lot commence par une sélection soignée des fermes. Inspection à réception et tri par grade, couleur, calibre et défauts. Les produits avancent uniquement quand la spécification est respectée.\n\n## Produits frais\nLa chaleur de champ est évacuée rapidement. Lavage, nettoyage, calibrage et emballage suivent des protocoles produit. Ventilation, calage et résistance au gerbage sont spécifiés par emballage.\n\n## Surgelés\nLe procédé IQF garde les grains séparés et la texture intacte. Stockage à −18 °C avec chaîne du froid ininterrompue jusqu'à destination.\n\n## Produits transformés\nLes lignes longue conservation suivent recette convenue, poids net maîtrisé, traitement thermique, sertissage et DLUO documentée.\n\n## Vérification\nProtection d'emballage, exactitude d'étiquetage et relevés de température sont vérifiés avant chargement. La documentation voyage avec chaque expédition."),
 'packaging-logistics' => $L(
  "# Packaging & Logistics\n\n## Pack formats\nFresh lines ship in ventilated and telescopic cartons, mesh bags, punnets and clamshells sized to the sales channel. Frozen products use IQF cartons with liners; processed goods use retail cans, glass jars, pouches, drums or bulk formats.\n\n## Labelling\nLabels carry product identity, net weight, ingredients where applicable, origin, lot and date coding, prepared to the destination market's requirements. Private-label artwork is confirmed with the buyer before production.\n\n## Cold chain\nPre-cooling, set points, ventilation patterns and maximum transit windows are planned per product before the first pallet moves. Frozen goods hold an unbroken −18 °C chain.\n\n## Documentation\nShipments travel with packing lists, commercial invoices, certificates of origin, and phytosanitary or health certificates where required.\n\n## Coordination\nContainer booking, loading supervision and arrival follow-up are coordinated by the export team so questions have answers while shipments are moving.",
  "# التعبئة واللوجستيات\n\n## صيغ التعبئة\nتُشحن خطوط الطازج في كراتين مهواة وتلسكوبية وأكياس شبكية وعبوات صغيرة وصدفية بحجم قناة البيع. تستخدم المنتجات المجمدة كراتين IQF مبطنة، والمصنعة عبوات معدنية وبرطمانات زجاجية وأكياس وبراميل أو صيغ سائبة.\n\n## البطاقة\nتحمل البطاقة هوية المنتج والوزن الصافي والمكونات عند الاقتضاء والمنشأ والدفعة وترميز التاريخ وفق متطلبات سوق الوجهة، وتُؤكد أعمال العلامة الخاصة مع المشتري قبل الإنتاج.\n\n## سلسلة التبريد\nيُخطط التبريد المسبق ونقاط الضبط وأنماط التهوية وأقصى فترات عبور لكل منتج قبل تحرك أول طبلة، وتُحفظ المجمدات بسلسلة −18 °م غير منقطعة.\n\n## المستندات\nترافق الشحنات قوائم تعبئة وفواتير تجارية وشهادات منشأ وشهادات نباتية أو صحية عند الحاجة.\n\n## التنسيق\nينسق فريق التصدير حجز الحاويات والإشراف على التحميل ومتابعة الوصول لتبقى للأسئلة إجابات أثناء حركة الشحنات.",
  "# Emballage & logistique\n\n## Formats d'emballage\nLe frais part en cartons ventilés et télescopiques, filets, barquettes et clapets calibrés selon le canal. Les surgelés utilisent des cartons IQF doublés ; les produits transformés, boîtes métal, bocaux, sachets, fûts ou vrac.\n\n## Étiquetage\nLes étiquettes portent identité produit, poids net, ingrédients le cas échéant, origine, lot et codage date, selon les exigences du marché de destination. Les maquettes MDD sont validées avec l'acheteur avant production.\n\n## Chaîne du froid\nPré-refroidissement, consignes, ventilation et fenêtres de transit maximales sont planifiés par produit avant la première palette. Les surgelés maintiennent une chaîne −18 °C ininterrompue.\n\n## Documentation\nLes expéditions voyagent avec listes de colisage, factures commerciales, certificats d'origine et certificats phytosanitaires ou sanitaires si requis.\n\n## Coordination\nRéservation de conteneurs, supervision du chargement et suivi à l'arrivée sont coordonnés par l'équipe export."),
 'seasonal-availability' => $L(
  "# Seasonal Availability\n\nEgyptian growing seasons give Nile-Maple long supply windows across the year. Below are the current planning windows — request a live confirmation for your volume and destination.\n\n## Fresh fruits\nCitrus leads the winter programme (Nov–Apr), stone fruits and melons the spring and summer (Apr–Sep), and grapes run May–Aug. Strawberries supply Nov–Mar.\n\n## Fresh vegetables\nPotatoes and onions run almost year-round; tomatoes and peppers peak Jan–Jun; artichokes Oct–Mar; leafy vegetables in the cool season.\n\n## Frozen coverage\nIQF lines preserve the harvest so vegetables and fruits remain available even when fresh windows close — the fastest way to secure year-round supply.\n\n| Season | Key fresh windows |\n| --- | --- |\n| Nov–Mar | Citrus, strawberries, artichokes, leafy vegetables |\n| Mar–Jun | Stone fruits, melons, tomatoes, peppers, onions |\n| Jun–Sep | Grapes, figs, dates, summer vegetables |\n| Sep–Nov | Autumn vegetables, late citrus preparation |",
  "# التوافر الموسمي\n\nتمنح مواسم الزراعة المصرية نيل مابل فترات توريد طويلة عبر العام. أدناه فترات التخطيط الحالية — اطلب تأكيدًا فعليًا لكميتك ووجهتك.\n\n## الفواكه الطازجة\nتقود الحمضيات برنامج الشتاء (نوفمبر–أبريل)، وتقود الفاكهة ذات النواة والشمام الربيع والصيف (أبريل–سبتمبر)، ويمتد العنب مايو–أغسطس، وتتوفر الفراولة نوفمبر–مارس.\n\n## الخضروات الطازجة\nتتوفر البطاطس والبصل طوال العام تقريبًا؛ وتبلغ الطماطم والفلفل ذروتهما يناير–يونيو؛ والخرشوف أكتوبر–مارس؛ والخضروات الورقية في الموسم البارد.\n\n## التغطية المجمدة\nتحفظ خطوط IQF المحصول فتبقى الخضروات والفواكه متاحة حتى عند إغلاق فترات الطازج — أسرع طريقة لتأمين توريد طوال العام.\n\n| الموسم | فترات الطازج الرئيسية |\n| --- | --- |\n| نوفمبر–مارس | حمضيات، فراولة، خرشوف، خضروات ورقية |\n| مارس–يونيو | فاكهة ذات نواة، شمام، طماطم، فلفل، بصل |\n| يونيو–سبتمبر | عنب، تين، بلح، خضروات صيفية |\n| سبتمبر–نوفمبر | خضروات خريفية، تحضير حمضيات متأخرة |",
  "# Disponibilité saisonnière\n\nLes saisons égyptiennes offrent à Nile-Maple de longues fenêtres d'approvisionnement. Voici les fenêtres de planification actuelles — demandez une confirmation en direct pour votre volume et destination.\n\n## Fruits frais\nLes agrumes mènent l'hiver (nov–avr), les fruits à noyau et melons le printemps et l'été (avr–sep), le raisin mai–août. Les fraises sont disponibles nov–mars.\n\n## Légumes frais\nPommes de terre et oignons presque toute l'année ; tomates et poivrons en pointe jan–juin ; artichauts oct–mars ; feuilles en saison fraîche.\n\n## Couverture surgelée\nLes lignes IQF préservent la récolte : légumes et fruits restent disponibles quand les fenêtres du frais se ferment — le moyen le plus rapide de sécuriser un approvisionnement annuel.\n\n| Saison | Fenêtres fraîches clés |\n| --- | --- |\n| Nov–mars | Agrumes, fraises, artichauts, feuilles |\n| Mars–juin | Fruits à noyau, melons, tomates, poivrons, oignons |\n| Juin–sep | Raisins, figues, dattes, légumes d'été |\n| Sep–nov | Légumes d'automne, préparation agrumes tardifs |"),
 'export-documentation' => $L(
  "# Export Documentation\n\n## Standard pack\nEvery shipment travels with: commercial invoice, packing list, certificate of origin, and transport documents for the mode used.\n\n## Product-specific certificates\nFresh produce carries phytosanitary certificates from the competent authority. Frozen and processed foods carry health certificates and, where the destination requires them, laboratory analyses and production records.\n\n## Labelling compliance\nDestination-market labelling — language, identity, weight, ingredients, origin, lot and date coding — is confirmed against the buyer's specification before production runs.\n\n## Preparation timeline\nDocumentation is prepared in parallel with packing, not after it. Certificates are requested early so loading is never delayed by paperwork.\n\n## Buyer coordination\nThe export team confirms the document set with each buyer before the first order and keeps the file updated for repeat shipments.",
  "# مستندات التصدير\n\n## الحزمة القياسية\nترافق كل شحنة: فاتورة تجارية، قائمة تعبئة، شهادة منشأ، ومستندات النقل للوسيلة المستخدمة.\n\n## شهادات خاصة بالمنتج\nتحمل المنتجات الطازجة شهادات صحية نباتية من الجهة المختصة، وتحمل المجمدة والمصنعة شهادات صحية وتحاليل مختبر وسجلات إنتاج عند طلب الوجهة.\n\n## مطابقة البطاقة\nتُأكد بطاقة سوق الوجهة — اللغة والهوية والوزن والمكونات والمنشأ والدفعة وترميز التاريخ — مقابل مواصفة المشتري قبل بدء الإنتاج.\n\n## الجدول الزمني للتجهيز\nتُجهز المستندات بالتوازي مع التعبئة لا بعدها، وتُطلب الشهادات مبكرًا حتى لا يتأخر التحميل بالأوراق.\n\n## التنسيق مع المشتري\nيؤكد فريق التصدير حزمة المستندات مع كل مشترٍ قبل أول طلب ويحدّث الملف للشحنات المتكررة.",
  "# Documentation export\n\n## Pack standard\nChaque expédition voyage avec : facture commerciale, liste de colisage, certificat d'origine et documents de transport du mode utilisé.\n\n## Certificats produit\nLe frais porte les certificats phytosanitaires de l'autorité compétente. Surgelés et transformés portent certificats sanitaires et, si la destination l'exige, analyses laboratoire et relevés de production.\n\n## Conformité d'étiquetage\nL'étiquetage du marché de destination — langue, identité, poids, ingrédients, origine, lot et codage date — est validé contre la spécification acheteur avant production.\n\n## Calendrier de préparation\nLa documentation est préparée en parallèle de l'emballage, jamais après. Les certificats sont demandés tôt pour qu'aucun chargement ne soit retardé.\n\n## Coordination acheteur\nL'équipe export confirme le jeu documentaire avec chaque acheteur avant la première commande et tient le dossier à jour."),
 'privacy' => $L(
  "# Privacy Policy\n\n## Data we collect\nWe collect only what we need to answer enquiries and operate this website: the information you submit in forms (name, organisation, contact details, message), and technical logs (IP address, browser) used for security and spam prevention.\n\n## How we use it\nYour data is used to respond to enquiries, prepare quotations and fulfil orders. We do not sell personal data or share it with advertisers.\n\n## Cookies\nA language-preference cookie keeps your site language; a consent cookie records your cookie choice. No advertising or cross-site tracking cookies are used.\n\n## Retention\nEnquiry records are kept for as long as commercially necessary, then deleted. Security logs are retained for a limited period.\n\n## Your rights\nYou may request access to or deletion of your personal data by emailing the address in our footer. We respond within one working day.\n\n## Contact\nQuestions about this policy: email us via the contact details published on every page of this website.",
  "# سياسة الخصوصية\n\n## البيانات التي نجمعها\nنجمع فقط ما يلزم للرد على الاستفسارات وتشغيل الموقع: المعلومات التي ترسلها في النماذج (الاسم والجهة وبيانات التواصل والرسالة)، وسجلات تقنية (عنوان IP والمتصفح) تستخدم للأمان ومنع الإساءة.\n\n## كيفية الاستخدام\nتُستخدم بياناتك للرد على الاستفسارات وإعداد عروض الأسعار وتنفيذ الطلبات. لا نبيع البيانات الشخصية ولا نشاركها مع المعلنين.\n\n## ملفات تعريف الارتباط\nيحفظ ملف ارتباط تفضيل اللغة اختيارك، ويسجل ملف آخر موافقتك على الكوكيز. لا تُستخدم كوكيز إعلانية أو تتبع عبر المواقع.\n\n## الاحتفاظ\nتُحفظ سجلات الاستفسارات للمدة التجارية اللازمة ثم تُحذف، وتُحفظ سجلات الأمان لفترة محدودة.\n\n## حقوقك\nيمكنك طلب الاطلاع على بياناتك أو حذفها عبر البريد المنشور في التذييل، ونرد خلال يوم عمل واحد.\n\n## التواصل\nلأي سؤال حول هذه السياسة راسلنا عبر بيانات الاتصال المنشورة في كل صفحات الموقع.",
  "# Politique de confidentialité\n\n## Données collectées\nNous collectons uniquement le nécessaire pour répondre aux demandes et faire fonctionner ce site : informations de formulaire (nom, organisation, coordonnées, message) et journaux techniques (adresse IP, navigateur) pour la sécurité et l'anti-spam.\n\n## Utilisation\nVos données servent à répondre aux demandes, préparer les devis et exécuter les commandes. Nous ne vendons ni ne partageons vos données avec des annonceurs.\n\n## Cookies\nUn cookie de préférence de langue conserve votre choix ; un cookie de consentement enregistre votre décision. Aucun cookie publicitaire ni de tracking inter-sites.\n\n## Conservation\nLes demandes sont conservées le temps commercialement nécessaire puis supprimées. Les journaux de sécurité ont une durée limitée.\n\n## Vos droits\nVous pouvez demander l'accès ou la suppression de vos données par e-mail (coordonnées en pied de page). Réponse sous un jour ouvré.\n\n## Contact\nPour toute question sur cette politique, écrivez-nous via les coordonnées publiées sur chaque page du site."),
 'terms' => $L(
  "# Terms of Use\n\n## Acceptance\nBy using this website you accept these terms. If you do not accept them, please do not use the site.\n\n## Use of the site\nThis website presents Nile-Maple's products and services. Content may not be copied, republished or used commercially without written permission. Reasonable use for procurement evaluation is welcome.\n\n## Product information\nSpecifications, availability windows and packing formats shown here are indicative. Final terms are confirmed in quotations and contracts, which prevail over website content.\n\n## No warranty\nThe site is provided on an as-available basis. We work to keep information accurate and current, but quotations and contracts govern commercial commitments.\n\n## Limitation of liability\nTo the extent permitted by law, Nile-Maple is not liable for indirect losses arising from use of this website.\n\n## Governing law\nThese terms are governed by the laws of the Arab Republic of Egypt.\n\n## Contact\nQuestions about these terms: use the contact details published in the website footer.",
  "# شروط الاستخدام\n\n## القبول\nباستخدام هذا الموقع فإنك تقبل هذه الشروط؛ وإن لم تقبلها فيرجى عدم استخدام الموقع.\n\n## استخدام الموقع\nيعرض الموقع منتجات وخدمات نيل مابل. لا يجوز نسخ المحتوى أو إعادة نشره أو استخدامه تجاريًا دون إذن كتابي، ويُرحب بالاستخدام المعقول لأغراض تقييم الشراء.\n\n## معلومات المنتجات\nالمواصفات وفترات التوافر وصيغ التعبئة المعروضة استرشادية. تُؤكد الشروط النهائية في عروض الأسعار والعقود التي تسود على محتوى الموقع.\n\n## إخلاء الضمان\nيُوفر الموقع كما هو متاح. نعمل على دقة المعلومات وحداثتها، لكن عروض الأسعار والعقود هي التي تحكم الالتزامات التجارية.\n\n## حدود المسؤولية\nفي حدود ما يسمح به القانون، لا تُسأل نيل مابل عن الخسائر غير المباشرة الناتجة عن استخدام هذا الموقع.\n\n## القانون الحاكم\nتخضع هذه الشروط لقوانين جمهورية مصر العربية.\n\n## التواصل\nلأي سؤال حول هذه الشروط استخدم بيانات الاتصال المنشورة في تذييل الموقع.",
  "# Conditions d'utilisation\n\n## Acceptation\nL'utilisation de ce site vaut acceptation de ces conditions. À défaut, merci de ne pas l'utiliser.\n\n## Utilisation du site\nCe site présente les produits et services Nile-Maple. Le contenu ne peut être copié, republié ou exploité commercialement sans autorisation écrite. L'usage raisonnable pour évaluation d'achat est bienvenu.\n\n## Informations produit\nSpécifications, fenêtres de disponibilité et formats d'emballage sont indicatifs. Les conditions finales sont confirmées dans devis et contrats, qui prévalent sur le contenu du site.\n\n## Absence de garantie\nLe site est fourni tel que disponible. Nous nous efforçons de maintenir l'information exacte, mais devis et contrats régissent les engagements commerciaux.\n\n## Limitation de responsabilité\nDans la limite permise par la loi, Nile-Maple n'est pas responsable des pertes indirectes liées à l'utilisation du site.\n\n## Loi applicable\nCes conditions sont régies par les lois de la République arabe d'Égypte.\n\n## Contact\nPour toute question, utilisez les coordonnées publiées en pied de page."),
];
foreach ($pages as $code => $body) {
    $blocks[] = ['zone' => 'page:' . $code, 'kind' => 'markdown', 'base' => [], 'title' => null, 'eyebrow' => null,
        'payload' => $L(['body' => $body['en']], ['body' => $body['ar']], ['body' => $body['fr']])];
}

/* ---------------- blog posts ---------------- */
$posts = [
 ['title' => $L('How to Read a Citrus Export Programme', 'كيف تقرأ برنامج تصدير الحمضيات', 'Comment lire un programme d’export d’agrumes'),
  'excerpt' => $L('Variety, maturity window, packing and temperature — the four things that decide citrus arrival condition.', 'الصنف وفترة النضج والتعبئة والحرارة — أربعة عوامل تحدد حالة وصول الحمضيات.', 'Variété, fenêtre de maturité, emballage et température : les quatre clés de l’arrivée des agrumes.'),
  'body' => $L(
"Citrus buying decisions look simple — price per box — but arrival condition is decided long before the container is stuffed. Four variables matter, and professional buyers evaluate them in this order.\n\n## 1. Variety, not just fruit\nNavel oranges, Valencia oranges and Spanish Honey Murcott mandarins behave differently in transit. Navel ships earlier in the season with thicker peel protection; Valencia holds juice longer into spring. Ask suppliers which variety you are actually buying and what its transit tolerance is.\n\n## 2. Maturity window\nFruit picked too early never reaches full flavour; fruit picked late loses firmness. A disciplined programme harvests to commercial maturity — colour, brix and firmness — not to calendar convenience.\n\n## 3. Packing and ventilation\nCartons must breathe. Telescopic, open-top and single-layer packs each manage humidity differently, and the wrong choice shows up as condensation damage at arrival. Match the pack to transit time.\n\n## 4. Temperature discipline\nTypical citrus moves at 3–9 °C depending on the line. Pre-cooling removes field heat before the container is loaded; set points must hold through the voyage. One broken chain undoes three good decisions.\n\nWhen you compare offers, compare these four answers — not just the price. A supplier who can state variety, harvest window, pack logic and temperature guide is describing a programme; one who cannot is describing a guess.",
"تبدو قرارات شراء الحمضيات بسيطة — سعر الكرتونة — لكن حالة الوصول تُحسم قبل تحميل الحاوية بوقت طويل. أربعة متغيرات مهمة، ويقيّمها المشترون المحترفون بهذا الترتيب.\n\n## 1. الصنف لا الثمرة فقط\nيتصرف برتقال نافيل وفالنسيا وماندرين سبانيش هني مركوت بشكل مختلف أثناء النقل. يُشحن نافيل مبكرًا بقشرة أسمك حمايةً، وتحتفظ فالنسيا بالعصير لفترة أطول في الربيع. اسأل المورد عن الصنف الذي تشتريه فعلًا وعن تحمله للنقل.\n\n## 2. فترة النضج\nالثمرة التي تُقطف مبكرًا لا تصل إلى النكهة الكاملة، والمتأخرة تفقد الصلابة. البرنامج المنضبط يحصد عند النضج التجاري — اللون والسكريات والصلابة — لا وفق تقويم مريح.\n\n## 3. التعبئة والتهوية\nيجب أن تتنفس الكراتين. تدير العبوات التلسكوبية والمفتوحة وذات الطبقة الواحدة الرطوبة بشكل مختلف، ويظهر الخطأ كضرر تكثف عند الوصول. طابق العبوة مع زمن العبور.\n\n## 4. انضباط الحرارة\nتنتقل الحمضيات عادة عند 3–9 °م حسب الخط. يزيل التبريد المسبق حرارة الحقل قبل التحميل، ويجب أن تصمد نقاط الضبط خلال الرحلة. انقطاع واحد في السلسلة يمحو ثلاثة قرارات جيدة.\n\nعند مقارنة العروض قارن هذه الإجابات الأربع — لا السعر وحده. المورد الذي يحدد الصنف وفترة الحصاد ومنطق التعبئة ودليل الحرارة يصف برنامجًا؛ ومن لا يستطيع يصف تخمينًا.",
"Les décisions d'achat d'agrumes paraissent simples — prix au carton — mais l'état à l'arrivée se joue bien avant l'empotage. Quatre variables comptent, et les acheteurs professionnels les évaluent dans cet ordre.\n\n## 1. La variété, pas seulement le fruit\nOranges navel, Valencia et mandarines Spanish Honey Murcott se comportent différemment en transit. La navel part tôt avec une peau épaisse protectrice ; la Valencia tient son jus plus longtemps au printemps. Demandez quelle variété vous achetez réellement et sa tolérance au transport.\n\n## 2. La fenêtre de maturité\nUn fruit cueilli trop tôt n'atteint jamais sa pleine saveur ; cueilli tard, il perd en fermeté. Un programme discipliné récolte à maturité commerciale — couleur, brix, fermeté — pas selon le calendrier.\n\n## 3. Emballage et ventilation\nLes cartons doivent respirer. Télescopiques, ouverts ou simple couche gèrent l'humidité différemment, et le mauvais choix se voit en condensation à l'arrivée. Adaptez l'emballage au temps de transit.\n\n## 4. Discipline thermique\nLes agrumes voyagent typiquement à 3–9 °C selon la ligne. Le pré-refroidissement évacue la chaleur avant chargement ; les consignes doivent tenir tout le voyage. Une chaîne rompue annule trois bonnes décisions.\n\nQuand vous comparez des offres, comparez ces quatre réponses — pas seulement le prix. Un fournisseur qui précise variété, fenêtre de récolte, logique d'emballage et guide thermique décrit un programme ; sinon, il décrit une supposition."),
  'media' => 'profile/image2.jpg'],
 ['title' => $L('IQF vs Fresh: Securing Year-Round Supply', 'المجمد IQF مقابل الطازج: تأمين توريد طوال العام', 'IQF vs frais : sécuriser l’approvisionnement annuel'),
  'excerpt' => $L('When fresh windows close, frozen lines keep your programme running — if the chain is right.', 'عندما تُغلق فترات الطازج تبقي الخطوط المجمدة برنامجك يعمل — إذا كانت السلسلة صحيحة.', 'Quand les fenêtres du frais se ferment, le surgelé maintient votre programme — si la chaîne suit.'),
  'body' => $L(
"Importers plan around harvest calendars, but demand does not pause when a fresh window closes. That is the commercial case for IQF.\n\n## What IQF actually preserves\nIndividually quick frozen processing freezes each piece separately and fast, so grains stay separate, cell structure survives, and texture holds through storage at −18 °C. Slow freezing does the opposite: crystals grow, cells rupture, and the product arrives mushy.\n\n## Matching the channel\nFood-service buyers value portioning and consistency; retail buyers value presentation and shelf messaging. Both are served by the same frozen line with different pack formats — 1 kg retail pouches, 5 kg food-service cartons, or bulk for further processing.\n\n## Planning the mix\nA resilient programme blends fresh windows with frozen coverage: peak-season fresh for margin and presentation, IQF for the months outside the window. Ask your supplier for the harvest calendar per line and plan frozen orders two to three months ahead of the fresh gap.\n\n## Chain discipline\nFrozen quality lives or dies on the chain. Storage, container set points and handling at destination must hold −18 °C without interruption. Request temperature records with every shipment and inspect on arrival.\n\nThe best importers do not choose between fresh and frozen — they choose both, timed correctly.",
"يخطط المستوردون حول تقويمات الحصاد، لكن الطلب لا يتوقف عندما تُغلق فترة طازج. هنا تبرز القيمة التجارية للمجمد IQF.\n\n## ما الذي يحفظه IQF فعلًا\nيجمد التصنيع الفردي السريع كل قطعة منفردة وبسرعة، فتبقى الحبات منفصلة ويصمد التركيب الخلوي ويثبت القوام خلال التخزين عند −18 °م. التجميد البطيء يفعل العكس: تنمو البلورات وتتمزق الخلايا ويصل المنتج مهروسًا.\n\n## مطابقة القناة\nيقدّر مشترو القطاع الغذائي التجزئة والاتساق، ويقدّر مشترو التجزئة العرض ورسالة الرف. تخدمهما الخطوط المجمدة نفسها بصيغ تعبئة مختلفة — أكياس 1 كجم للتجزئة، كراتين 5 كجم للقطاع الغذائي، أو سائب للتصنيع.\n\n## تخطيط المزيج\nالبرنامج المرن يدمج فترات الطازج مع التغطية المجمدة: طازج ذروة الموسم للهامش والعرض، وIQF للشهور خارج الفترة. اطلب من المورد تقويم الحصاد لكل خط وخطط طلبات المجمد قبل فجوة الطازج بشهرين إلى ثلاثة.\n\n## انضباط السلسلة\nتعيش جودة المجمد أو تموت على السلسلة. يجب أن يحفظ التخزين وضبط الحاويات والتداول في الوجهة −18 °م دون انقطاع. اطلب سجلات الحرارة مع كل شحنة وافحص عند الوصول.\n\nأفضل المستوردين لا يختارون بين الطازج والمجمد — يختارون كليهما بتوقيت صحيح.",
"Les importateurs planifient selon les calendriers de récolte, mais la demande ne s'arrête pas quand une fenêtre du frais se ferme. C'est le cas commercial de l'IQF.\n\n## Ce que l'IQF préserve vraiment\nLa surgélation individuelle rapide congèle chaque pièce séparément et vite : grains séparés, structure cellulaire préservée, texture tenue à −18 °C. La congélation lente fait l'inverse — cristaux, cellules rompues, produit mou à l'arrivée.\n\n## Adapter au canal\nLe food-service valorise portionnage et constance ; le détail, présentation et message rayon. Les deux sont servis par la même ligne surgelée avec des formats différents — sachets 1 kg détail, cartons 5 kg food-service, vrac pour transformation.\n\n## Planifier le mix\nUn programme résilient combine fenêtres du frais et couverture surgelée : frais de pointe pour la marge et la présentation, IQF pour les mois hors fenêtre. Demandez le calendrier de récolte par ligne et planifiez les commandes surgelées deux à trois mois avant le creux du frais.\n\n## Discipline de chaîne\nLa qualité du surgelé vit ou meurt avec la chaîne. Stockage, consignes conteneur et manutention à destination doivent tenir −18 °C sans interruption. Exigez les relevés de température et inspectez à l'arrivée.\n\nLes meilleurs importateurs ne choisissent pas entre frais et surgelé — ils choisissent les deux, au bon moment."),
  'media' => 'profile/image3.jpg'],
 ['title' => $L('Egyptian Vegetables: A Buyer’s Handling Checklist', 'الخضروات المصرية: قائمة فحص تداول للمشترين', 'Légumes égyptiens : checklist manutention acheteur'),
  'excerpt' => $L('Seven questions that separate a well-handled container from a claims file.', 'سبعة أسئلة تفصل الحاوية جيدة التداول عن ملف المطالبات.', 'Sept questions qui séparent un conteneur bien géré d’un dossier de réclamation.'),
  'body' => $L(
"Vegetables forgive less than fruit. Moisture, respiration and mechanical damage compound quickly over a transit. Use this checklist with any supplier.\n\n## 1. What happens between harvest and cooling?\nField heat is the enemy. Ask how quickly produce reaches pre-cooling after harvest and what the set point is.\n\n## 2. How is the lot sorted?\nGrade, colour, size and defect screening should be documented. Ask what percentage is typically culled — a supplier who cannot answer is not sorting.\n\n## 3. Which pack, and why?\nVentilated cartons for respiration-heavy lines; mesh bags for onions and potatoes; single-layer trays for delicate fruit-vegetables. The answer should reference the product, not the habit.\n\n## 4. What is the transit window?\nEvery line has a maximum. If your route exceeds it, the product should change (frozen or processed form), not the excuse.\n\n## 5. How is humidity managed?\nToo dry shrivels; too wet rots. Liners, vents and pallet patterns are the tools — ask which are used.\n\n## 6. What documentation arrives?\nPacking lists, phytosanitary certificates, origin certificates and transport records should be confirmed before loading.\n\n## 7. What happens when something arrives wrong?\nClaims are inevitable in agriculture; silence is not an acceptable response. Agree the notification window, photo protocol and resolution process in writing before the first shipment.\n\nA supplier who answers all seven fluently is running a system. That system — not luck — is what delivers condition at arrival.",
"الخضروات أقل تسامحًا من الفاكهة. تتضاعف الرطوبة والتنفس والأضرار الميكانيكية سريعًا خلال العبور. استخدم هذه القائمة مع أي مورد.\n\n## 1. ماذا يحدث بين الحصاد والتبريد؟\nحرارة الحقل هي العدو. اسأل عن سرعة وصول المنتج إلى التبريد المسبق وعن نقطة الضبط.\n\n## 2. كيف تُفرز الدفعة؟\nيجب أن يكون فرز الدرجة واللون والحجم والعيوب موثقًا. اسأل عن نسبة الاستبعاد المعتادة — المورد الذي لا يجيب لا يفرز.\n\n## 3. أي عبوة ولماذا؟\nكراتين مهواة للخطوط عالية التنفس؛ أكياس شبكية للبصل والبطاطس؛ صوانٍ بطبقة واحدة للخضروات الثمرية الحساسة. يجب أن تشير الإجابة إلى المنتج لا إلى العادة.\n\n## 4. ما فترة العبور؟\nلكل خط حد أقصى. إذا تجاوز خطك الملاحي هذا الحد، يجب أن يتغير المنتج (صيغة مجمدة أو مصنعة) لا العذر.\n\n## 5. كيف تُدار الرطوبة؟\nالجفاف يذبل والرطوبة تعفن. البطانات والفتحات وأنماط الرص هي الأدوات — اسأل أيها يُستخدم.\n\n## 6. ما المستندات التي تصل؟\nيجب تأكيد قوائم التعبئة والشهادات النباتية وشهادات المنشأ وسجلات النقل قبل التحميل.\n\n## 7. ماذا يحدث إذا وصل شيء خاطئ؟\nالمطالبات حتمية في الزراعة؛ أما الصمت فليس ردًا مقبولًا. اتفق على فترة الإخطار وبروتوكول الصور وإجراءات الحل كتابيًا قبل أول شحنة.\n\nالمورد الذي يجيب عن السبعة بطلاقة يدير نظامًا. هذا النظام — لا الحظ — هو ما يوصل الحالة السليمة عند الوصول.",
"Les légumes pardonnent moins que les fruits. Humidité, respiration et dommages mécaniques s'accumulent vite en transit. Utilisez cette checklist avec tout fournisseur.\n\n## 1. Que se passe-t-il entre récolte et refroidissement ?\nLa chaleur de champ est l'ennemie. Demandez le délai d'accès au pré-refroidissement et la consigne.\n\n## 2. Comment le lot est-il trié ?\nGrade, couleur, calibre et défauts doivent être documentés. Demandez le pourcentage d'écart typique — un fournisseur qui ne répond pas ne trie pas.\n\n## 3. Quel emballage, et pourquoi ?\nCartons ventilés pour les lignes à forte respiration ; filets pour oignons et pommes de terre ; plateaux simple couche pour les légumes-fragiles. La réponse doit citer le produit, pas l'habitude.\n\n## 4. Quelle fenêtre de transit ?\nChaque ligne a un maximum. Si votre route le dépasse, c'est le produit qui doit changer (forme surgelée ou transformée), pas l'excuse.\n\n## 5. Comment l'humidité est-elle gérée ?\nTrop sec flétrit ; trop humide pourrit. Doublures, évents et schémas de palettisation sont les outils — demandez lesquels.\n\n## 6. Quelle documentation arrive ?\nColisage, certificats phytosanitaires, certificats d'origine et relevés de transport sont confirmés avant chargement.\n\n## 7. Que se passe-t-il en cas d'arrivée non conforme ?\nLes réclamations sont inévitables en agriculture ; le silence n'est pas une réponse acceptable. Convenez par écrit du délai de notification, du protocole photo et du processus de résolution avant la première expédition.\n\nUn fournisseur qui répond aux sept couramment fait tourner un système. C'est ce système — pas la chance — qui livre l'état à l'arrivée."),
  'media' => 'profile/image5.jpg'],
 ['title' => $L('Private Label: Getting Packaging Right the First Time', 'العلامة الخاصة: ضبط التعبئة من المرة الأولى', 'Marque distributeur : réussir l’emballage du premier coup'),
  'excerpt' => $L('A repeatable checklist for artwork, compliance and pack performance.', 'قائمة قابلة للتكرار للأعمال الفنية والمطابقة وأداء العبوة.', 'Une checklist reproductible pour maquettes, conformité et performance d’emballage.'),
  'body' => $L(
"Private-label programmes fail most often at packaging, not product. The fix is process.\n\n## Specify before you design\nStart with the commercial brief: channel, shelf position, pack size and price point. Packaging decisions cascade from these — not from artwork taste.\n\n## Compliance first\nDestination-market labelling rules govern language, identity statement, net weight declaration, ingredient lists where applicable, origin marking, lot and date coding, and any required marks or registration numbers. Build the label template from the regulation, then add branding.\n\n## Artwork discipline\nWork in vector formats, confirm colour references (Pantone or measured values), and require a physical or high-fidelity proof before the production run. A screen approval is not a print approval.\n\n## Pack performance testing\nThe pack must survive palletisation, container stacking and destination handling. Test compression and drop performance on the actual pack, not a similar one.\n\n## Version control\nEvery artwork change gets a version number and a written approval. This single habit prevents the most expensive category of private-label error: producing the old label.\n\nDo these five steps in order and private label becomes a repeatable programme rather than a negotiation about whose fault the last shipment was.",
"تفشل برامج العلامة الخاصة غالبًا في التعبئة لا في المنتج. والحل عملية منهجية.\n\n## واصل قبل أن تصمم\nابدأ بالملخص التجاري: القناة وموقع الرف وحجم العبوة والسعر. تتفرع قرارات التعبئة من هذه — لا من ذوق الأعمال الفنية.\n\n## المطابقة أولًا\nتحكم قواعد بطاقة سوق الوجهة اللغة وبيان الهوية وإعلان الوزن الصافي وقوائم المكونات عند الاقتضاء وعلامة المنشأ والدفعة وترميز التاريخ وأي علامات أو أرقام تسجيل مطلوبة. ابنِ قالب البطاقة من اللائحة ثم أضف العلامة.\n\n## انضباط الأعمال الفنية\nاعمل بصيغ متجهة وأكد مراجع الألوان (بانتون أو قيم مقاسة) واطلب نسخة مادية أو عالية الدقة قبل الإنتاج. الموافقة على الشاشة ليست موافقة على الطباعة.\n\n## اختبار أداء العبوة\nيجب أن تصمد العبوة أمام التطبيل ورص الحاويات وتداول الوجهة. اختبر الانضغاط والسقوط على العبوة الفعلية لا على عبوة مشابهة.\n\n## ضبط النسخ\nكل تغيير في العمل الفني يحصل على رقم نسخة وموافقة كتابية. هذه العادة وحدها تمنع أغلى فئة أخطاء في العلامة الخاصة: طباعة البطاقة القديمة.\n\nنفذ هذه الخطوات الخمس بالترتيب فتصبح العلامة الخاصة برنامجًا قابلًا للتكرار بدل تفاوض حول خطأ من في الشحنة الأخيرة.",
"Les programmes MDD échouent le plus souvent sur l'emballage, pas sur le produit. La solution est méthodologique.\n\n## Spécifier avant de dessiner\nPartez du brief commercial : canal, position rayon, taille de pack et prix. Les décisions d'emballage en découlent — pas du goût artistique.\n\n## Conformité d'abord\nLes règles d'étiquetage du marché de destination régissent langue, dénomination, poids net, ingrédients le cas échéant, marquage d'origine, lot et codage date, marques ou numéros d'enregistrement requis. Construisez le gabarit d'étiquette à partir de la réglementation, puis ajoutez la marque.\n\n## Discipline des maquettes\nTravaillez en vectoriel, confirmez les références couleur (Pantone ou valeurs mesurées) et exigez un bon à tirer physique ou haute fidélité avant production. Une validation écran n'est pas une validation print.\n\n## Tests de performance\nL'emballage doit survivre à la palettisation, au gerbage conteneur et à la manutention à destination. Testez compression et chute sur le pack réel, pas un pack similaire.\n\n## Gestion des versions\nChaque changement de maquette reçoit un numéro de version et une approbation écrite. Cette habitude évite l'erreur MDD la plus coûteuse : produire l'ancienne étiquette.\n\nCes cinq étapes dans l'ordre font de la MDD un programme reproductible plutôt qu'une négociation sur la faute du dernier conteneur."),
  'media' => 'profile/image4.jpg'],
 ['title' => $L('Cold Chain: What Actually Breaks It', 'سلسلة التبريد: ما الذي يكسرها فعلًا', 'Chaîne du froid : ce qui la rompt vraiment'),
  'excerpt' => $L('The four failure points — and the records that prove a chain held.', 'نقاط الفشل الأربع — والسجلات التي تثبت صمود السلسلة.', 'Les quatre points de rupture — et les relevés qui prouvent la tenue.'),
  'body' => $L(
"Cold chain failures are rarely dramatic. They accumulate in small, preventable moments.\n\n## Failure point 1: the loading dock\nThe most common break is between cold store and container: produce waiting on an ambient dock while paperwork completes. The fix is scheduling — pre-cooled containers, staged loading, and dock doors that close.\n\n## Failure point 2: set-point drift\nReefer units are set, then adjusted for fuel economy or misread instructions. Every adjustment should be logged with time, operator and reason. Unlogged adjustments are how disputes start.\n\n## Failure point 3: airflow blockage\nOver-stuffed pallets and blocked vents create warm pockets inside a cold container. Load plans with airflow channels are not optional for respiration-heavy vegetables.\n\n## Failure point 4: destination handling\nThe chain does not end at the port. Customs holds, cross-docking and local transport are where well-managed shipments get undone. Agree destination procedures with the consignee in advance.\n\n## The records that settle arguments\nTemperature data loggers, set-point logs, loading photographs and transit times, kept per shipment, turn most claims conversations into short ones. Require them from every logistics partner.\n\nCold chain is not equipment. It is procedure — and procedures are what buyers should audit.",
"نادرًا ما تكون كسور سلسلة التبريد درامية. تتراكم في لحظات صغيرة قابلة للمنع.\n\n## نقطة الفشل 1: رصيف التحميل\nأشهر انقطاع بين المخزن البارد والحاوية: منتج ينتظر على رصيف بدرجة محيطية بينما تكتمل الأوراق. الحل جدولة — حاويات مبردة مسبقًا وتحميل مجدول وأبواب رصيف تُغلق.\n\n## نقطة الفشل 2: انحراف نقطة الضبط\nتُضبط وحدات التبريد ثم تُعدّل لتوفير الوقود أو بسوء قراءة التعليمات. يجب تسجيل كل تعديل بالوقت والمشغل والسبب. التعديلات غير المسجلة هي بداية النزاعات.\n\n## نقطة الفشل 3: انسداد تدفق الهواء\nتخلق الطبلات المكتظة والفتحات المسدودة جيوبًا دافئة داخل حاوية باردة. خطط التحميل بممرات هواء ليست اختيارية للخضروات عالية التنفس.\n\n## نقطة الفشل 4: تداول الوجهة\nلا تنتهي السلسلة في الميناء. فترات التخليص والنقل العرضي والنقل المحلي هي حيث تُهدر الشحنات جيدة الإدارة. اتفق على إجراءات الوجهة مع المرسل إليه مسبقًا.\n\n## السجلات التي تحسم الجدال\nمسجلات بيانات الحرارة وسجلات نقاط الضبط وصور التحميل وأزمنة العبور، المحفوظة لكل شحنة، تحوّل معظم محادثات المطالبات إلى محادثات قصيرة. اطلبها من كل شريك لوجستي.\n\nسلسلة التبريد ليست معدات. إنها إجراءات — والإجراءات هي ما يجب على المشترين تدقيقه.",
"Les ruptures de chaîne du froid sont rarement spectaculaires. Elles s'accumulent en petits moments évitables.\n\n## Point de rupture 1 : le quai de chargement\nLa rupture la plus courante se situe entre chambre froide et conteneur : produit en attente sur quai ambiant pendant la paperasse. La solution est l'ordonnancement — conteneurs pré-refroidis, chargement planifié, portes de quai fermées.\n\n## Point de rupture 2 : dérive des consignes\nLes groupes froid sont réglés, puis ajustés pour l'économie de carburant ou sur instructions mal lues. Chaque ajustement doit être journalisé : heure, opérateur, motif. Les ajustements non journalisés déclenchent les litiges.\n\n## Point de rupture 3 : obstruction du flux d'air\nPalettes surchargées et évents bouchés créent des poches chaudes dans un conteneur froid. Les plans de chargement avec couloirs d'air ne sont pas optionnels pour les légumes à forte respiration.\n\n## Point de rupture 4 : manutention à destination\nLa chaîne ne s'arrête pas au port. Attentes douanières, cross-docking et transport local défont des expéditions bien gérées. Convenez des procédures de destination avec le consignataire à l'avance.\n\n## Les relevés qui tranchent\nData-loggers de température, journaux de consignes, photos de chargement et temps de transit, archivés par expédition, raccourcissent la plupart des discussions de réclamation. Exigez-les de chaque partenaire logistique.\n\nLa chaîne du froid n'est pas un équipement. C'est une procédure — et les procédures sont ce que les acheteurs doivent auditer."),
  'media' => 'profile/image1.jpg'],
 ['title' => $L('Choosing Pack Formats by Sales Channel', 'اختيار صيغ التعبئة حسب قناة البيع', 'Choisir les formats d’emballage par canal de vente'),
  'excerpt' => $L('Retail, food-service and processing buyers need different packs — a practical guide.', 'مشترو التجزئة والقطاع الغذائي والتصنيع يحتاجون عبوات مختلفة — دليل عملي.', 'Détail, food-service et industrie ont besoin de packs différents — guide pratique.'),
  'body' => $L(
"The same product sells through channels that want opposite things from packaging. Getting this wrong costs margin or kills the sale.\n\n## Retail\nShelf presence rules: consumer pack sizes (500 g–2 kg typical), clean graphics, barcodes, tamper evidence and stackability. Presentation damage tolerance is low — one crushed clamshell is one lost sale.\n\n## Food-service\nKitchen efficiency rules: 2.5–10 kg formats, easy opening, portioning guidance, resealability where practical, and durability over beauty. Chefs forgive plain packs; they do not forgive packs that slow service.\n\n## Industrial processing\nCost and consistency rule: bulk formats, liners that empty cleanly, lot traceability and specification sheets that survive audit. Presentation is irrelevant; repeatability is everything.\n\n## Cross-channel pitfalls\nDo not retail-pack an industrial order (you are paying for graphics nobody sees) and do not bulk-pack retail (you are asking the store to rework). Private label sits between: retail presentation with your specification discipline.\n\n## Asking the right question\nBefore quoting, every professional supplier asks: which channel, which pack size, which market? If your supplier does not ask, you are buying a habit, not a solution.",
"يُباع المنتج نفسه عبر قنوات تريد أشياء متعاكضة من التعبئة. الخطأ هنا يكلف الهامش أو يقتل البيع.\n\n## التجزئة\nيحكم حضور الرف: أحجام عبوات استهلاكية (500 جم–2 كجم عادة)، رسوميات نظيفة، باركود، دليل عدم عبث، وقابلية رص. تحمل أضرار العرض منخفض — عبوة صدفيه مهشومة واحدة بيع خاسر واحد.\n\n## القطاع الغذائي\nتحكم كفاءة المطبخ: صيغ 2.5–10 كجم، فتح سهل، إرشاد تجزئة، إعادة إغلاق عند العملية، ومتانة فوق الجمال. الطهاة يغفرون العبوات البسيطة؛ ولا يغفرون عبوات تبطئ الخدمة.\n\n## التصنيع\nتحكم التكلفة والاتساق: صيغ سائبة، بطانات تفرغ نظيفًا، تتبع دفعات، وأوراق مواصفة تصمد أمام التدقيق. العرض غير مهم؛ التكرارية كل شيء.\n\n## مزالق بين القنوات\nلا تعبئ طلبًا صناعيًا بتعبئة تجزئة (تدفع مقابل رسوميات لا يراها أحد) ولا تعبئ التجزئة سائبًا (تطلب من المتجر إعادة التجهيز). العلامة الخاصة تقع بينهما: عرض تجزئة بانضباط مواصفتك.\n\n## السؤال الصحيح\nقبل أي عرض سعر يسأل كل مورد محترف: أي قناة؟ أي حجم عبوة؟ أي سوق؟ إذا لم يسأل موردك فأنت تشتري عادة لا حلًا.",
"Le même produit se vend via des canaux qui attendent l'opposé de l'emballage. Se tromper coûte la marge ou tue la vente.\n\n## Détail\nLa présence en rayon commande : formats consommateur (500 g–2 kg typique), graphisme propre, codes-barres, inviolabilité et gerbabilité. La tolérance aux dommages de présentation est faible — une barquette écrasée est une vente perdue.\n\n## Food-service\nL'efficacité cuisine commande : formats 2,5–10 kg, ouverture facile, guidage de portionnage, refermeture si pratique, et durabilité avant beauté. Les chefs pardonnent un pack sobre ; jamais un pack qui ralentit le service.\n\n## Industrie\nLe coût et la constance commandent : formats vrac, doublures qui se vident proprement, traçabilité lot et fiches de spécification qui survivent à l'audit. La présentation est hors sujet ; la répétabilité est tout.\n\n## Pièges inter-canaux\nN'emballage pas une commande industrielle en pack détail (vous payez un graphisme que personne ne voit) ni du détail en vrac (vous demandez au magasin de retravailler). La MDD se situe entre : présentation détail avec votre discipline de spécification.\n\n## La bonne question\nAvant de chiffrer, tout fournisseur professionnel demande : quel canal, quel format, quel marché ? Si le vôtre ne demande pas, vous achetez une habitude, pas une solution."),
  'media' => 'profile/image2.jpg'],
];


/* ---------------- two more briefs so the blog launches with 8 (D-10) ---------------- */
$posts[] = ['title' => $L('Seasonal Windows: What Egypt Ships, and When', 'النوافذ الموسمية: ماذا تُصدّر مصر ومتى', 'Fenêtres saisonnières : ce que l’Égypte exporte, et quand'),
  'excerpt' => $L('A month-by-month reading of the Egyptian harvest calendar and how to plan orders around it.', 'قراءة شهرية لتقويم الحصاد المصري وكيفية تخطيط الطلبات حوله.', 'Lecture mois par mois du calendrier égyptien et comment planifier vos commandes.'),
  'body' => $L(
"Egypt's advantage is not one crop — it is a calendar. Mild winters let field vegetables and citrus move into European markets while northern supply is thin, and the hot, dry summer drives potatoes, onions and melons.\n\n## Winter (Dec–Feb): citrus and potatoes\nOranges, mandarins and lemons are at peak, with early potatoes and onions following. This is the window where a mixed programme works best: citrus for volume and recognition, potatoes for continuity.\n\n## Spring (Mar–May): the transition\nCitrus tails off, and green beans, peppers, tomatoes and melons take over. Cold-chain behaviour changes with ambient temperature at harvest, so pre-cooling discipline matters more, not less, as the season warms.\n\n## Summer (Jun–Aug): storage crops\nOnions, potatoes and garlic lead, with mangoes and grapes in the air-freight window. This is also when frozen IQF lines protect your shelf: the fresh gap is structural, not accidental.\n\n## Autumn (Sep–Nov): restart\nEarly citrus, pomegranates, grapes and the first field vegetables. Contracts signed in this window usually secure the best citrus programmes of the following winter.\n\n## Planning rule\nLock volumes two seasons ahead, keep one line in frozen cover for every fresh line you depend on, and re-check packing specifications each time the ambient temperature at harvest changes by five degrees.\n\nA buyer who reads the calendar buys better: fewer substitutions, firmer pricing, fewer surprises at arrival.",
"ميزة مصر ليست محصولًا واحدًا بل تقويم. الشتاء المعتدل يسمح للخضروات الحقليه والحمضيات بدخول الأسواق الأوروبية بينما يقل العرض الشمالي، والصيف الحار الجاف يدفع البطاطس والبصل والبطيخ.\n\n## الشتاء (ديسمبر–فبراير): حمضيات وبطاطس\nالبرتقال والماندرين والليمون في ذروتها، تليها بطاطس وبصل مبكر. هنا يعمل البرنامج المختلط أفضل شكل: حمضيات للحجم والتعرف، وبطاطس للاستمرارية.\n\n## الربيع (مارس–مايو): الانتقال\nتنتهي الحمضيات تدريجيًا وتحل الفاصوليا الخضراء والفلفل والطماطم والبطيخ. يتغير سلوك السلسلة الباردة مع حرارة الحصاد، فيصير التبريد المسبق أهم لا أقل مع ارتفاع الحرارة.\n\n## الصيف (يونيو–أغسطس): محاصيل التخزين\nيقودها البصل والبطاطس والثوم، مع مانجو وعنب في نافذة الشحن الجوي. وهنا تحمي خطوط IQF رفوفك: الفجوة في الطازج بنيوية لا عرضية.\n\n## الخريف (سبتمبر–نوفمبر): البداية الجديدة\nحمضيات مبكرة ورمان وعنب وأول خضروات حقلية. العقود الموقعة في هذه النافذة تؤمن عادة أفضل برامج الحمضيات في الشتاء التالي.\n\n## قاعدة التخطيط\nأثبت الكميات قبل موسمين، وأبقِ خطًا مجمدًا مقابل كل خط طازج تعتمد عليه، وأعد مراجعة مواصفات التعبئة كلما تغيرت حرارة الحصاد بخمس درجات.\n\nمن يقرأ التقويم يشتري أفضل: بدائل أقل، تسعير أثبت، ومفاجآت أقل عند الوصول.",
"L'avantage de l'Égypte n'est pas une culture mais un calendrier. Des hivers doux permettent aux légumes de plein champ et aux agrumes d'entrer en Europe quand l'offre nordique se raréfie, et l'été chaud et sec porte pommes de terre, oignons et melons.\n\n## Hiver (déc–fév) : agrumes et pommes de terre\nOranges, mandarines et citrons sont à leur pic, suivis des pommes de terre et oignons primeurs. C'est la fenêtre où un programme mixte fonctionne le mieux : les agrumes pour le volume, la pomme de terre pour la continuité.\n\n## Printemps (mar–mai) : la transition\nLes agrumes s'estompent, haricots verts, poivrons, tomates et melons prennent le relais. Le comportement de la chaîne du froid évolue avec la température à la récolte : le pré-refroidissement compte davantage, pas moins.\n\n## Été (juin–août) : cultures de conservation\nOignons, pommes de terre et ail dominent, mangues et raisins en fret aérien. C'est aussi quand l'IQF protège vos rayons : le creux du frais est structurel, pas accidentel.\n\n## Automne (sep–nov) : redémarrage\nAgrumes précoces, grenades, raisins et premiers légumes de plein champ. Les contrats signés ici sécurisent les meilleurs programmes d'agrumes de l'hiver suivant.\n\n## Règle de planification\nVerrouillez les volumes deux saisons à l'avance, gardez une ligne surgelée pour chaque ligne fraîche dont vous dépendez, et revoyez les spécifications d'emballage dès que la température de récolte bouge de cinq degrés.\n\nUn acheteur qui lit le calendrier achète mieux : moins de substitutions, un prix plus ferme, moins de surprises à l'arrivée."),
  'media' => 'profile/image3.jpg'];

$posts[] = ['title' => $L('The Export Paper Pack: Documents That Clear Customs Faster', 'ملف التصدير الورقي: مستندات تُسرّع التخليص الجمركي', 'Le dossier export : les documents qui accélèrent le dédouanement'),
  'excerpt' => $L('Phytosanitary certificate, certificate of origin, packing list, invoice — what each one must say.', 'الشهادة фитوسانية وشهادة المنشأ وقائمة التعبئة والفاتورة — ما يجب أن يقوله كل مستند.', 'Certificat phytosanitaire, certificat d’origine, packing list, facture — ce que chacun doit dire.'),
  'body' => $L(
"Paperwork does not sell fruit, but it can stop it at a border for four days. Most consignments that lose time at arrival do not lose it to a defect — they lose it to a mismatch between documents.\n\n## Phytosanitary certificate\nThe core import document for fresh produce. It must name the commodity and variety as you declared, the origin, the treatment (if required) and the declared quantity. Any divergence from the packing list becomes a question to answer at the border.\n\n## Certificate of origin\nDetermines the duty regime. For preferential agreements, wording is prescribed — the declaration text must appear verbatim, and the exporter's statement must match the invoice exactly.\n\n## Commercial invoice\nIncoterm, unit price, currency, weight (net and gross), package count, and the HS code. The HS code is where most disputes start: it must match the receiving authority's tariff schedule, not the shipper's habit.\n\n## Packing list\nWeights and counts per lot, pallet configuration, and lot codes traceable to the harvest block. A clean packing list is also a recall insurance policy: it turns a wide search into a narrow one.\n\n## Bill of lading and temperature clauses\nCheck the set point stated on the booking appears on the carrier's documents. Where the voyage record differs, that document is the one that wins a claim.\n\n## The discipline that saves days\nSend drafts before the container is stuffed, not after. Confirm names, codes and weights match across every document, then lock them. Buyers who do this rarely speak to a customs broker — and buyers who skip it always do.",
"الأوراق لا تبيع الثمار، لكنها قد توقفها أربعة أيام عند الحدود. أغلب الشحنات التي تفقد وقتًا عند الوصول لا تفقده بسبب عيب، بل بسبب اختلاف بين المستندات.\n\n## الشهادة الصحية النباتية\nالمستند الأساسي للاستيراد في الحاصلات الطازجة. يجب أن تسمّي المحصول والصنف كما صرّحت، والمنشأ، والمعاملة (إن لزم)، والكمية المعلنة. أي اختلاف عن قائمة التعبئة يصبح سؤالًا تجيب عنه عند الحدود.\n\n## شهادة المنشأ\nتحدد نظام الرسوم. وفي اتفاقات الأفضلية تكون الصياغة مقررة: نص الإقرار يجب أن يرد حرفيًا، وبيان المصدّر يطابق الفاتورة تمامًا.\n\n## الفاتورة التجارية\nشرط التسليم، سعر الوحدة، العملة، الأوزان الصافية والإجمالية، عدد الطرود، ورقم النظام المنسق. وهنا تبدأ أغلب الخلافات: يجب أن يطابق الرقم جدول جهة الاستيراد لا عادة الشاحن.\n\n## قائمة التعبئة\nأوزان وكميات لكل دفعة، وتكوين المنصات، ورموز الدفعات المتتبِّعة إلى قطعة الحصاد. قائمة التعبئة النظيفة تأمين ضد السحب أيضًا: تحوّل البحث الواسع إلى ضيّق.\n\n## بوليصة الشحن وبنود الحرارة\nتأكد أن نقطة الضبط الواردة في الحجز مكتوبة في مستندات الناقل. عند اختلاف سجل الرحلة، هذا هو المستند الذي يحسم المطالبة.\n\n## الانضباط الذي يوفر الأيام\nأرسل المسودات قبل تحميل الحاوية لا بعده. أثبت تطابق الأسماء والرموز والأوزان في كل المستندات، ثم أغلقها. المشترون الذين يفعلون ذلك نادرًا ما يتكلمون مع وكيل جمركي — والذين يتركونه يتحدثون دائمًا.",
"Le papier ne vend pas le fruit, mais il peut le bloquer quatre jours à la frontière. La plupart des lots qui perdent du temps à l’arrivée ne le perdent pas à cause d’un défaut, mais d’une divergence entre documents.\n\n## Certificat phytosanitaire\nDocument central de l’import de produits frais. Il doit nommer la denrée et la variété comme déclarées, l’origine, le traitement éventuel et la quantité déclarée. Tout écart avec le packing list devient une question à régler à la frontière.\n\n## Certificat d’origine\nIl détermine le régime douanier. Sous accord préférentiel, la formulation est imposée : la déclaration doit figurer verbatim et la mention de l’exportateur doit correspondre exactement à la facture.\n\n## Facture commerciale\nIncoterm, prix unitaire, devise, poids net et brut, nombre de colis et code SH. Le code SH est l’origine de la plupart des litiges : il doit correspondre au tarif de l’autorité de destination, pas à l’habitude de l’expéditeur.\n\n## Packing list\nPoids et quantités par lot, configuration palettes et codes de lot reliés à la parcelle de récolte. Un packing list propre est aussi une assurance rappel : il transforme une recherche large en recherche ciblée.\n\n## Connaissement et clauses de température\nVérifiez que la consigne indiquée dans la réservation figure sur les documents du transporteur. Si le journal de route diffère, c’est ce document qui tranche un litige.\n\n## La discipline qui fait gagner des jours\nEnvoyez les projets avant l’empotage, pas après. Faites confirmer la concordance des noms, codes et poids sur chaque document, puis figez-les. Les acheteurs qui le font ne parlent presque jamais à un transitaire en douane — les autres, toujours."),
  'media' => 'profile/image4.jpg'];

require __DIR__ . '/seed_content3.php';   // appends the remaining about:* zones to $blocks

return ['services' => $services, 'faqs' => $faqs, 'blocks' => $blocks, 'posts' => $posts, 'pages' => $pages];
