<?php
/**
 * Trilingual seed content (EN source-of-truth from DOCX; AR/FR professionally written
 * where structural, controlled-language baseline for per-product prose — decision D-14).
 */
$L = static fn(string $en, string $ar, string $fr) => ['en' => $en, 'ar' => $ar, 'fr' => $fr];

$categories = [
    'fresh-fruits' => [
        'icon' => 'citrus', 'accent' => 'green',
        'name' => $L('Fresh Fruits', 'الفواكه الطازجة', 'Fruits frais'),
        'slug' => $L('fresh-fruits', 'فواكه-طازجة', 'fruits-frais'),
        'headline' => $L('Selected produce. Careful handling. Reliable global supply.', 'حاصلات منتقاة. تداول حريص. توريد عالمي موثوق.', 'Produits sélectionnés, manipulation soignée, supply fiable.'),
        'summary' => $L('Citrus, mangoes, grapes, pomegranates, strawberries, dates, melons, stone fruits and other seasonal lines.',
            'حمضيات ومانجو وعنب ورمان وفراولة وبلح وبطيخ وفاكهة ذات نواة وخطوط موسمية أخرى.',
            'Agrumes, mangues, raisins, grenades, fraises, dattes, melons, fruits à noyau et autres lignes saisonnières.'),
        'meta_t' => $L('Fresh Fruits from Egypt | 31 Export Lines | Nile-Maple', 'فواكه طازجة من مصر | 31 خط تصدير | نيل مابل', 'Fruits frais d’Égypte | 31 références | Nile-Maple'),
        'meta_d' => $L('Egyptian fresh fruits for export: varieties, export handling, packing and cold-chain guides for 31 product lines.',
            'فواكه مصرية طازجة للتصدير: أصناف وتداول تصديري وتعبئة وأدلة سلسلة تبريد لـ31 خطًا.',
            'Fruits frais égyptiens à l’export : variétés, manipulation, emballage et chaîne du froid pour 31 références.'),
    ],
    'fresh-vegetables' => [
        'icon' => 'sprout', 'accent' => 'green',
        'name' => $L('Fresh Vegetables', 'الخضروات الطازجة', 'Légumes frais'),
        'slug' => $L('fresh-vegetables', 'خضروات-طازجة', 'legumes-frais'),
        'headline' => $L('Harvest condition, sorting, ventilation, temperature and pack strength.', 'حالة الحصاد والفرز والتهوية ودرجة الحرارة ومتانة العبوة.', 'État à la récolte, tri, ventilation, température et solidité d’emballage.'),
        'summary' => $L('Potatoes, onions, garlic, tomatoes, peppers, artichokes, leafy vegetables, legumes and specialty produce.',
            'بطاطس وبصل وثوم وطماطم وفلفل وخرشوف وخضروات ورقية وبقوليات وحاصلات متخصصة.',
            'Pommes de terre, oignons, ail, tomates, poivrons, artichauts, feuilles, légumineuses et spécialités.'),
        'meta_t' => $L('Fresh Vegetables from Egypt | 37 Export Lines | Nile-Maple', 'خضروات طازجة من مصر | 37 خط تصدير | نيل مابل', 'Légumes frais d’Égypte | 37 références | Nile-Maple'),
        'meta_d' => $L('Egyptian fresh vegetables for export with handling, packing and cold-chain specifications for 37 lines.',
            'خضروات مصرية طازجة للتصدير مع مواصفات تداول وتعبئة وسلسلة تبريد لـ37 خطًا.',
            'Légumes frais égyptiens à l’export avec spécifications de manipulation, emballage et chaîne du froid.'),
    ],
    'frozen-products' => [
        'icon' => 'snowflake', 'accent' => 'pine',
        'name' => $L('Frozen Products', 'المنتجات المجمدة', 'Produits surgelés'),
        'slug' => $L('frozen-products', 'منتجات-مجمدة', 'produits-surgeles'),
        'headline' => $L('Rapid freezing, stable frozen storage and an uninterrupted cold chain.', 'تجميد سريع وتخزين مجمد مستقر وسلسلة تبريد غير منقطعة.', 'Surgélation rapide, stockage stable et chaîne du froid ininterrompue.'),
        'summary' => $L('IQF fruits, vegetables, herbs, mixed vegetables and buyer-specific blends.',
            'فواكه وخضروات وأعشاب مجمدة IQF وخلطات خضروات وخلطات حسب طلب المشتري.',
            'Fruits, légumes, herbes IQF, mélanges et blends spécifiques acheteurs.'),
        'meta_t' => $L('IQF Frozen Products from Egypt | 36 Lines | Nile-Maple', 'منتجات مجمدة IQF من مصر | 36 خطًا | نيل مابل', 'Produits surgelés IQF d’Égypte | 36 références | Nile-Maple'),
        'meta_d' => $L('Egyptian IQF frozen fruits, vegetables, herbs and mixes with forms, processing and frozen-chain guides.',
            'فواكه وخضروات وأعشاب وخلطات مصرية مجمدة IQF مع أشكال وتصنيع وأدلة سلسلة تجميد.',
            'Fruits, légumes, herbes et mélanges IQF égyptiens avec formes, transformation et guide congélation.'),
    ],
    'processed-canned' => [
        'icon' => 'can', 'accent' => 'amber',
        'name' => $L('Manufactured, Processed & Canned Products', 'المنتجات المصنعة والمعالجة والمعلبة', 'Produits transformés & appertisés'),
        'slug' => $L('processed-canned', 'مصنعات-ومعلبات', 'transformes-appertises'),
        'headline' => $L('Recipe specification, fill weight, thermal processing, sealing, shelf life and labelling.',
            'مواصفة الوصفة والوزن والمعاجة الحرارية والإغلاق ومدة الصلاحية والبطاقة.',
            'Recette, poids net, traitement thermique, sertissage, DLUO et étiquetage.'),
        'summary' => $L('Canned vegetables and fruits, pickles, olives, sauces, juices, jams, spreads and pantry products.',
            'خضروات وفاكهة معلبة ومخللات وزيتون وصلصات وعصائر ومربى ومستلزمات مخزن.',
            'Légumes et fruits appertisés, pickles, olives, sauces, jus, confitures et épicerie.'),
        'meta_t' => $L('Processed & Canned Foods from Egypt | 55 Lines | Nile-Maple', 'مصنعات ومعلبات مصرية | 55 خطًا | نيل مابل', 'Produits transformés & appertisés d’Égypte | 55 références | Nile-Maple'),
        'meta_d' => $L('Egyptian canned, pickled and shelf-stable foods: forms, processing, packing and storage guides for 55 lines.',
            'معلبات ومخللات وأغذية مصرية طويلة الحفظ: أشكال وتصنيع وتعبئة وأدلة تخزين لـ55 خطًا.',
            'Appertisés, pickles et produits longue conservation égyptiens : formes, transformation, emballage, stockage.'),
    ],
];

/* 159 product names — AR / FR (trade-standard terminology) */
$N = static fn(string $ar, string $fr) => ['ar' => $ar, 'fr' => $fr];
$product_names = [
 'ORANGE' => $N('برتقال', 'Orange'), 'MANDARIN / TANGERINE' => $N('ماندرين / يوسفي', 'Mandarine / Clémentine'),
 'SPANISH HONEY MURCOTT MANDARIN' => $N('ماندرين سبانيش هني مركوت', 'Mandarine Spanish Honey Murcott'),
 'LEMON' => $N('ليمون', 'Citron'), 'LIME' => $N('ليمون أخضر (لايم)', 'Lime'), 'GRAPEFRUIT' => $N('جريب فروت', 'Pamplemousse'),
 'MANGO' => $N('مانجو', 'Mangue'), 'GRAPES' => $N('عنب', 'Raisin de table'), 'POMEGRANATE' => $N('رمان', 'Grenade'),
 'STRAWBERRY' => $N('فراولة', 'Fraise'), 'FRESH DATES' => $N('بلح طازج', 'Dattes fraîches'), 'GUAVA' => $N('جوافة', 'Goyave'),
 'FIG' => $N('تين', 'Figue'), 'PEACH' => $N('خوخ', 'Pêche'), 'NECTARINE' => $N('نكتارين', 'Nectarine'),
 'APRICOT' => $N('مشمش', 'Abricot'), 'PLUM' => $N('برقوق', 'Prune'), 'CHERRY' => $N('كرز', 'Cerise'),
 'WATERMELON' => $N('بطيخ', 'Pastèque'), 'CANTALOUPE' => $N('كانتلوب', 'Cantaloup'), 'HONEYDEW MELON' => $N('شمام هانيديو', 'Melon honeydew'),
 'CUSTARD APPLE' => $N('قشطة (أنونا)', 'Pomme cannelle'), 'PERSIMMON / KAKI' => $N('كاكا (برسيمون)', 'Kaki / Persimmon'),
 'PRICKLY PEAR' => $N('تين شوكي', 'Figue de Barbarie'), 'LYCHEE' => $N('ليتشي', 'Litchi'), 'APPLE' => $N('تفاح', 'Pomme'),
 'PEAR' => $N('كمثرى', 'Poire'), 'KIWIFRUIT' => $N('كيوي', 'Kiwi'), 'AVOCADO' => $N('أفوكادو', 'Avocat'),
 'BANANA' => $N('موز', 'Banane'), 'PINEAPPLE' => $N('أناناس', 'Ananas'),
 'POTATO' => $N('بطاطس', 'Pomme de terre'), 'SWEET POTATO' => $N('بطاطا حلوة', 'Patate douce'), 'ONION' => $N('بصل', 'Oignon'),
 'SPRING ONION' => $N('بصل أخضر', 'Oignon nouveau'), 'SHALLOT' => $N('شالوت', 'Échalote'), 'GARLIC' => $N('ثوم', 'Ail'),
 'LEEK' => $N('كراث', 'Poireau'), 'CARROT' => $N('جزر', 'Carotte'), 'BEETROOT' => $N('بنجر', 'Betterave'),
 'RADISH' => $N('فجل', 'Radis'), 'TURNIP' => $N('لفت', 'Navet'), 'TOMATO' => $N('طماطم', 'Tomate'),
 'CHERRY TOMATO' => $N('طماطم شيري', 'Tomate cerise'), 'BELL PEPPER / CAPSICUM' => $N('فلفل رومي', 'Poivron'),
 'CHILI PEPPER' => $N('فلفل حار', 'Piment'), 'CUCUMBER' => $N('خيار', 'Concombre'), 'ZUCCHINI / COURGETTE' => $N('كوسة', 'Courgette'),
 'EGGPLANT / AUBERGINE' => $N('باذنجان', 'Aubergine'), 'OKRA' => $N('بامية', 'Gombo'), 'SWEET CORN' => $N('ذرة حلوة', 'Maïs doux'),
 'GREEN BEANS' => $N('فاصوليا خضراء', 'Haricots verts'), 'GREEN PEAS' => $N('بازلاء', 'Petits pois'),
 'SNOW PEAS / MANGETOUT' => $N('بازلاء الثلج', 'Pois mangetout'), 'SUGAR SNAP PEAS' => $N('بازلاء سكرية', 'Pois gourmands'),
 'BROAD BEANS' => $N('فول أخضر', 'Fèves'), 'BROCCOLI' => $N('بروكلي', 'Brocoli'), 'CAULIFLOWER' => $N('قرنبيط', 'Chou-fleur'),
 'CABBAGE' => $N('كرنب', 'Chou'), 'BRUSSELS SPROUTS' => $N('كرنب بروكسل', 'Choux de Bruxelles'),
 'ICEBERG LETTUCE' => $N('خس آيسبرج', 'Salade iceberg'), 'ROMAINE LETTUCE' => $N('خس رومين', 'Salade romaine'),
 'SPINACH' => $N('سبانخ', 'Épinards'), 'CELERY' => $N('كرفس', 'Céleri'), 'ARTICHOKE' => $N('خرشوف', 'Artichaut'),
 'FENNEL' => $N('شمر', 'Fenouil'), 'FRESH MOLOKHIA / JUTE MALLOW' => $N('ملوخية طازجة', 'Molokhia fraîche (corète)'),
 'FRESH HERBS' => $N('أعشاب طازجة', 'Herbes fraîches'),
 'FROZEN OKRA' => $N('بامية مجمدة', 'Gombo surgelé'), 'FROZEN MOLOKHIA' => $N('ملوخية مجمدة', 'Molokhia surgelée'),
 'FROZEN GREEN PEAS' => $N('بازلاء مجمدة', 'Petits pois surgelés'), 'FROZEN GREEN BEANS' => $N('فاصوليا خضراء مجمدة', 'Haricots verts surgelés'),
 'FROZEN CARROTS' => $N('جزر مجمد', 'Carottes surgelées'), 'FROZEN PEAS & CARROTS' => $N('بازلاء وجزر مجمدات', 'Petits pois et carottes surgelés'),
 'FROZEN MIXED VEGETABLES' => $N('خضروات مشكلة مجمدة', 'Légumes mélangés surgelés'), 'FROZEN SPINACH' => $N('سبانخ مجمدة', 'Épinards surgelés'),
 'FROZEN BROCCOLI' => $N('بروكلي مجمد', 'Brocoli surgelé'), 'FROZEN CAULIFLOWER' => $N('قرنبيط مجمد', 'Chou-fleur surgelé'),
 'FROZEN ARTICHOKE' => $N('خرشوف مجمد', 'Artichauts surgelés'), 'FROZEN YELLOW SWEET CORN' => $N('ذرة حلوة صفراء مجمدة', 'Maïs doux jaune surgelé'),
 'FROZEN BROAD BEANS' => $N('فول أخضر مجمد', 'Fèves surgelées'), 'FROZEN TARO CUBES' => $N('مكعبات قلقاس مجمدة', 'Cubes de taro surgelés'),
 'FROZEN FRENCH FRIES & POTATO PRODUCTS' => $N('بطاطس مقلية مجمدة ومنتجات بطاطس', 'Frites surgelées & produits de pomme de terre'),
 'FROZEN ONION' => $N('بصل مجمد', 'Oignons surgelés'), 'FROZEN BELL PEPPER' => $N('فلفل رومي مجمد', 'Poivrons surgelés'),
 'FROZEN ZUCCHINI' => $N('كوسة مجمدة', 'Courgettes surgelées'), 'FROZEN GRILLED EGGPLANT' => $N('باذنجان مشوي مجمد', 'Aubergines grillées surgelées'),
 'FROZEN STRAWBERRY' => $N('فراولة مجمدة', 'Fraises surgelées'), 'FROZEN MANGO' => $N('مانجو مجمدة', 'Mangues surgelées'),
 'FROZEN GUAVA' => $N('جوافة مجمدة', 'Goyaves surgelées'), 'FROZEN POMEGRANATE ARILS' => $N('حبوب رمان مجمدة', 'Grains de grenade surgelés'),
 'FROZEN FIG' => $N('تين مجمد', 'Figues surgelées'), 'FROZEN APRICOT' => $N('مشمش مجمد', 'Abricots surgelés'),
 'FROZEN PEACH' => $N('خوخ مجمد', 'Pêches surgelées'), 'FROZEN GRAPES' => $N('عنب مجمد', 'Raisins surgelés'),
 'FROZEN BLUEBERRY' => $N('توت أزرق مجمد', 'Myrtilles surgelées'), 'FROZEN RASPBERRY' => $N('توت العليق مجمد', 'Framboises surgelées'),
 'FROZEN BLACKBERRY' => $N('توت أسود مجمد', 'Mûres surgelées'), 'FROZEN PINEAPPLE' => $N('أناناس مجمد', 'Ananas surgelé'),
 'FROZEN MIXED BERRIES' => $N('توت مشكل مجمد', 'Fruits rouges mélangés surgelés'),
 'FROZEN TROPICAL FRUIT MIX' => $N('خليط فواكه استوائية مجمد', 'Mélange de fruits tropicaux surgelé'),
 'FROZEN MEDITERRANEAN VEGETABLE MIX' => $N('خليط خضروات متوسطي مجمد', 'Mélange de légumes méditerranéens surgelé'),
 'FROZEN STIR-FRY VEGETABLE MIX' => $N('خليط خضروات ستير-فراي مجمد', 'Mélange stir-fry surgelé'),
 'CUSTOM FROZEN MIXES' => $N('خلطات مجمدة حسب الطلب', 'Mélanges surgelés sur mesure'),
 'CANNED FAVA BEANS' => $N('فول معلب', 'Fèves appertisées'), 'CANNED CHICKPEAS' => $N('حمص معلب', 'Pois chiches appertisés'),
 'CANNED WHITE BEANS' => $N('فاصوليا بيضاء معلبة', 'Haricots blancs appertisés'), 'CANNED RED KIDNEY BEANS' => $N('فاصوليا حمراء معلبة', 'Haricots rouges appertisés'),
 'CANNED GREEN PEAS' => $N('بازلاء معلبة', 'Petits pois appertisés'), 'CANNED SWEET CORN' => $N('ذرة حلوة معلبة', 'Maïs doux appertisé'),
 'CANNED GREEN BEANS' => $N('فاصوليا خضراء معلبة', 'Haricots verts appertisés'), 'CANNED MIXED VEGETABLES' => $N('خضروات مشكلة معلبة', 'Légumes mélangés appertisés'),
 'CANNED ARTICHOKES' => $N('خرشوف معلب', 'Artichauts appertisés'), 'CANNED GRAPE LEAVES' => $N('ورق عنب معلب', 'Feuilles de vigne appertisées'),
 'CANNED WHOLE TOMATOES' => $N('طماطم صحيحة معلبة', 'Tomates entières appertisées'), 'CANNED DICED TOMATOES' => $N('طماطم مقطعة معلبة', 'Tomates dés appertisées'),
 'CANNED MUSHROOMS' => $N('مشروم معلب', 'Champignons appertisés'), 'CANNED FRUIT COCKTAIL' => $N('كوكتيل فواكه معلب', 'Cocktail de fruits appertisé'),
 'CANNED PINEAPPLE' => $N('أناناس معلب', 'Ananas appertisé'), 'CANNED PEACHES' => $N('خوخ معلب', 'Pêches appertisées'),
 'TABLE OLIVES' => $N('زيتون مائدة', 'Olives de table'), 'STUFFED GREEN OLIVES' => $N('زيتون أخضر محشي', 'Olives vertes farcies'),
 'PICKLED CUCUMBERS / GHERKINS' => $N('مخلل خيار / كورنيش', 'Cornichons au vinaigre'), 'PICKLED ONIONS' => $N('مخلل بصل', 'Oignons au vinaigre'),
 'PICKLED PEPPERS' => $N('مخلل فلفل', 'Poivrons au vinaigre'), 'PICKLED JALAPENOS' => $N('مخلل هالبينو', 'Jalapeños au vinaigre'),
 'PICKLED LEMONS WITH SAFFLOWER' => $N('مخلل ليمون بالقرطوم', 'Citrons confits au carthame'), 'PICKLED TURNIPS' => $N('مخلل لفت', 'Navets au vinaigre'),
 'PICKLED CARROTS' => $N('مخلل جزر', 'Carottes au vinaigre'), 'PICKLED MIXED VEGETABLES' => $N('مخلل خضروات مشكل', 'Pickles de légumes mélangés'),
 'ARTICHOKES IN BRINE' => $N('خرشوف في محلول ملحي', 'Artichauts en saumure'), 'ROASTED RED PEPPERS' => $N('فلفل أحمر مشوي', 'Poivrons rouges rôtis'),
 'EGGPLANT MAKDOUS' => $N('مقدوس باذنجان', 'Makdous d’aubergine'), 'GRILLED EGGPLANT' => $N('باذنجان مشوي', 'Aubergines grillées'),
 'TOMATO PASTE' => $N('صلصة طماطم مركزة', 'Concentré de tomate'), 'TOMATO SAUCE' => $N('صوص طماطم', 'Sauce tomate'),
 'TOMATO PASSATA' => $N('طماطم باساتا', 'Passata de tomate'), 'PIZZA SAUCE' => $N('صوص بيتزا', 'Sauce pizza'),
 'TOMATO KETCHUP' => $N('كتشاب طماطم', 'Ketchup'), 'CHILI PASTE / HARISSA' => $N('شطة / هريسة', 'Harissa / pâte de piment'),
 'HOT SAUCE' => $N('صوص حار', 'Sauce piquante'), 'FRUIT JAM' => $N('مربى فواكه', 'Confiture de fruits'),
 'ORANGE MARMALADE' => $N('مربى برتقال', 'Marmelade d’orange'), 'DATE JAM' => $N('مربى بلح', 'Confiture de dattes'),
 'PRICKLY PEAR JAM' => $N('مربى تين شوكي', 'Confiture de figue de Barbarie'), 'BLACK MOLASSES' => $N('دبس أسود', 'Mélasse noire'),
 'NATURAL HONEY' => $N('عسل طبيعي', 'Miel naturel'), 'FRUIT JUICE' => $N('عصير فواكه', 'Jus de fruits'),
 'FRUIT NECTAR' => $N('رحيق فواكه', 'Nectar de fruits'), 'FRUIT CONCENTRATES' => $N('مركزات فواكه', 'Concentrés de fruits'),
 'FRUIT PUREES / PULPS' => $N('بيوريه / لب فواكه', 'Purées et pulpes de fruits'), 'TOMATO JUICE' => $N('عصير طماطم', 'Jus de tomate'),
 'FRUIT COCKTAIL DRINK' => $N('مشروب كوكتيل فواكه', 'Boisson cocktail de fruits'), 'OLIVE OIL' => $N('زيت زيتون', 'Huile d’olive'),
 'TAHINI' => $N('طحينة', 'Tahini'), 'HALVA' => $N('حلاوة طحينية', 'Halva'), 'HUMMUS' => $N('حمص بطحينة', 'Houmous'),
 'BABA GHANOUSH' => $N('بابا غنوج', 'Baba ghanoush'), 'NATURAL VINEGAR' => $N('خل طبيعي', 'Vinaigre naturel'),
];

/* packing glossary for AR/FR controlled rendering */
$packing_glossary = [
 /* Controlled pack vocabulary (Finalization-Plan §8.3.3): whole phrases first — PHP strtr
    tries longest keys first, so multi-word terms gloss as units and the output reads as
    native trade language instead of a word salad. Cultivar names (Valencia…), IQF and PET
    stay Latin on purpose — they are the trade names AR/FR buyers use. */
 'ar' => [
   'Ventilated cartons' => 'كراتين مهواة', 'ventilated cartons' => 'كراتين مهواة',
   'Ventilated cartons with dividers' => 'كراتين مهواة بفواصل',
   'telescopic boxes' => 'كراتين تلسكوبية', 'Telescopic cartons' => 'كراتين تلسكوبية', 'telescopic cartons' => 'كراتين تلسكوبية',
   'Telescopic' => 'تلسكوبية', 'telescopic' => 'تلسكوبية',
   'Open-top' => 'مفتوحة الأعلى', 'open-top' => 'مفتوحة الأعلى',
   'Tray-packed cartons' => 'كراتين معبأة في صوانٍ', 'tray-packed cartons' => 'كراتين معبأة في صوانٍ',
   'Tray-packed telescopic cartons' => 'كراتين تلسكوبية معبأة في صوانٍ',
   'Tray-packed export cartons' => 'كراتين تصدير معبأة في صوانٍ',
   'Tray-packed or layered cartons' => 'كراتين معبأة في صوانٍ أو طبقات',
   'Tray-packed' => 'معبأة في صوانٍ', 'tray-packed' => 'معبأة في صوانٍ',
   'Mesh bags' => 'أكياس شبكية', 'mesh bags' => 'أكياس شبكية', 'net packs' => 'أكياس شبكية',
   'Jumbo bags' => 'أكياس جامبو', 'jumbo bags' => 'أكياس جامبو',
   'Consumer packs' => 'عبوات تجزئة', 'consumer packs' => 'عبوات تجزئة', 'retail packs' => 'عبوات تجزئة',
   'Clamshell punnets' => 'عبوات صدفية', 'clamshell punnets' => 'عبوات صدفية', 'Clamshell' => 'صدفية',
   'Master cartons' => 'كراتين رئيسية', 'master cartons' => 'كراتين رئيسية',
   'carry bags' => 'أكياس محمولة', 'Carry bags' => 'أكياس محمولة',
   'with liners' => 'مبطنة', 'with dividers' => 'بفواصل', 'with protective trays' => 'بصوانٍ حامية',
   'Punnets' => 'عبوات صغيرة', 'punnets' => 'عبوات صغيرة',
   'Cartons' => 'كراتين', 'cartons' => 'كراتين', 'Carton' => 'كرتونة', 'cartons' => 'كراتين',
   'Boxes' => 'كراتين', 'boxes' => 'كراتين',
   'Bags' => 'أكياس', 'bags' => 'أكياس', 'perforated bags' => 'أكياس مثقبة',
   'Baskets' => 'أقفاص', 'Bins' => 'صناديق كبيرة', 'bins' => 'صناديق كبيرة',
   'Bulk bins' => 'صناديق سائبة كبيرة', 'bulk bins' => 'صناديق سائبة كبيرة',
   'Crates' => 'صناديق خشبية', 'crates' => 'صناديق خشبية', 'Crate' => 'صندوق خشبي',
   'Lined cartons' => 'كراتين مبطنة', 'lined cartons' => 'كراتين مبطنة',
   'lined crates' => 'صناديق خشبية مبطنة', 'Lined' => 'مبطنة', 'lined' => 'مبطنة',
   'reusable crates' => 'صناديق خشبية قابلة لإعادة الاستخدام',
   'Trays' => 'صوانٍ', 'trays' => 'صوانٍ', 'Tray' => 'صينية', 'protective trays' => 'صوانٍ حامية',
   'Pouches' => 'أكياس محكمة', 'pouches' => 'أكياس محكمة',
   'Retail bags' => 'أكياس تجزئة', 'food-service bags' => 'أكياس لقطاع الغذائي',
   'Retail blocks' => 'بلوكات تجزئة', 'Retail pouches' => 'أكياس تجزئة',
   'bulk cartons' => 'كراتين سائبة', 'lined bulk cartons' => 'كراتين سائبة مبطنة',
   'Retail cans' => 'علب تجزئة', 'food-service cans' => 'علب لقطاع الغذائي',
   'Drums' => 'براميل', 'Bulk' => 'سائب', 'bulk' => 'سائب', 'bulk formats' => 'صيغ سائبة',
   'bulk containers' => 'حاويات سائبة', 'aseptic bulk' => 'تعبئة أسبتية',
   'Single-layer' => 'بطبقة واحدة', 'single-layer' => 'بطبقة واحدة',
   'Layered cartons' => 'كراتين طبقات', 'layered cartons' => 'كراتين طبقات',
   'Cushioned cartons' => 'كراتين محمية', 'Protected export cartons' => 'كراتين تصدير محمية',
   'protected export cartons' => 'كراتين تصدير محمية', 'protected cartons' => 'كراتين محمية',
   'Shallow cartons' => 'كراتين ضحلة', 'Shallow' => 'ضحلة', 'shallow' => 'ضحلة',
   'Ventilated banana cartons' => 'كراتين موز مهواة',
   'Sleeved bunches' => 'حزم مغلفة', 'sleeved bunches' => 'حزم مغلفة',
   'Bunched' => 'حزم', 'bunched' => 'حزم', 'Bunches' => 'حزم', 'bunches' => 'حزم',
   'Braids' => 'ضفائر', 'Nets' => 'شبك', 'nets' => 'شبك',
   'secured pallet loads' => 'طبلات مثبتة', 'pallet loads' => 'طبلات',
   'Pallet' => 'طبلات', 'pallet' => 'طبلات',
   'Flow-wrapped trays' => 'صوانٍ مغلفة', 'Flow-wrapped' => 'مغلفة', 'flow-wrapped' => 'مغلفة',
   'Shrink-wrapped packs' => 'عبوات مغلفة حراريًا', 'shrink-wrapped packs' => 'عبوات مغلفة حراريًا',
   'Private-label retail' => 'تجزئة بعلامة خاصة', 'Private-label' => 'علامة خاصة', 'private label subject to agreement' => 'العلامة الخاصة بالاتفاق',
   'food-service containers' => 'حاويات لقطاع الغذائي', 'food-service' => 'لقطاع الغذائي', 'Food-service' => 'لقطاع الغذائي',
   'Retail' => 'تجزئة', 'retail' => 'تجزئة',
   'Glass jars' => 'برطمانات زجاجية', 'PET jars' => 'برطمانات PET', 'jars' => 'برطمانات',
   'Dark glass' => 'زجاج داكن', 'dark glass' => 'زجاج داكن', 'Glass' => 'زجاج', 'glass' => 'زجاج',
   'Cans' => 'علب', 'cans' => 'علب', 'Tins' => 'علب معدنية', 'tins' => 'علب معدنية',
   'plastic tubs' => 'أوعية بلاستيكية', 'Plastic tubs' => 'أوعية بلاستيكية', 'tubs' => 'أوعية',
   'Buckets' => 'دلاء', 'buckets' => 'دلاء', 'Bottles' => 'زجاجات', 'bottles' => 'زجاجات',
   'Containers' => 'حاويات', 'containers' => 'حاويات',
   'export cartons' => 'كراتين تصدير',
   'loose' => 'سائب', 'Loose' => 'سائب',
   /* exact composite strings (post-gloss residues): whole-phrase keys keep word order native */
   'Lined ventilated banana cartons' => 'كراتين موز مهواة مبطنة',
   'lined ventilated banana cartons' => 'كراتين موز مهواة مبطنة',
   'Paper bags' => 'أكياس ورقية', 'paper bags' => 'أكياس ورقية',
   'braids' => 'ضفائر', 'Braids' => 'ضفائر',
   'liners' => 'تبطين', 'Liners' => 'تبطين',
   'Cushioned cartons' => 'كراتين محمية', 'cushioned cartons' => 'كراتين محمية', 'cushioned' => 'محمية',
   'bushel-style boxes' => 'صناديق نمط بوشل', 'Bushel-style boxes' => 'صناديق نمط بوشل', 'bushel-style' => 'نمط بوشل',
   'Single-layer trays' => 'صوانٍ بطبقة واحدة', 'single-layer trays' => 'صوانٍ بطبقة واحدة',
   'Single-layer punnets' => 'عبوات صغيرة بطبقة واحدة', 'single-layer punnets' => 'عبوات صغيرة بطبقة واحدة',
   'Single-layer or protected export cartons' => 'كراتين تصدير بطبقة واحدة أو محمية',
   'single-layer or protected export cartons' => 'كراتين تصدير بطبقة واحدة أو محمية',
   'Cartons with liners' => 'كراتين مبطنة', 'cartons with liners' => 'كراتين مبطنة',
   'Punnets, bags or cartons with liners' => 'عبوات صغيرة أو أكياس أو كراتين مبطنة',
   'Punnets, bags or lined cartons' => 'عبوات صغيرة أو أكياس أو كراتين مبطنة',
   'Mesh bags, paper bags, cartons or jumbo bags' => 'أكياس شبكية أو ورقية أو كراتين أو أكياس جامبو',
   'Mesh bags, cartons, nets or braids' => 'أكياس شبكية أو كراتين أو شبك أو ضفائر',
   'Single-layer trays or cushioned cartons' => 'صوانٍ بطبقة واحدة أو كراتين محمية',
   'Tray-packed cartons or bushel-style boxes' => 'كراتين معبأة في صوانٍ أو صناديق نمط بوشل',
   'tray-packed cartons or bushel-style boxes' => 'كراتين معبأة في صوانٍ أو صناديق نمط بوشل',
   'Cartons with liners, punnets or carry bags' => 'كراتين مبطنة أو عبوات صغيرة أو أكياس محمولة',
   'cartons with liners, punnets or carry bags' => 'كراتين مبطنة أو عبوات صغيرة أو أكياس محمولة',
   ' or ' => ' أو ', ' with ' => ' مع ', ' in ' => ' في ', '; ' => '؛ ',
 ],
 'fr' => [
   'Ventilated cartons' => 'cartons ventilés', 'ventilated cartons' => 'cartons ventilés',
   'Ventilated cartons with dividers' => 'cartons ventilés avec séparations',
   'telescopic boxes' => 'cartons télescopiques', 'Telescopic cartons' => 'cartons télescopiques', 'telescopic cartons' => 'cartons télescopiques',
   'Telescopic' => 'télescopiques', 'telescopic' => 'télescopiques',
   'Open-top' => 'ouverts dessus', 'open-top' => 'ouverts dessus',
   'Tray-packed cartons' => 'cartons à plateaux', 'tray-packed cartons' => 'cartons à plateaux',
   'Tray-packed telescopic cartons' => 'cartons télescopiques à plateaux',
   'Tray-packed export cartons' => 'cartons export à plateaux',
   'Tray-packed or layered cartons' => 'cartons à plateaux ou en couches',
   'Tray-packed' => 'à plateaux', 'tray-packed' => 'à plateaux',
   'Mesh bags' => 'filets', 'mesh bags' => 'filets', 'net packs' => 'filets',
   'Jumbo bags' => 'sacs jumbo', 'jumbo bags' => 'sacs jumbo',
   'Consumer packs' => 'emballages consommateur', 'consumer packs' => 'emballages consommateur', 'retail packs' => 'packs détail',
   'Clamshell punnets' => 'barquettes clapet', 'clamshell punnets' => 'barquettes clapet', 'Clamshell' => 'clapet',
   'Master cartons' => 'cartons maîtres', 'master cartons' => 'cartons maîtres',
   'carry bags' => 'sacs de poche', 'Carry bags' => 'sacs de poche',
   'with liners' => 'doublés', 'with dividers' => 'avec séparations', 'with protective trays' => 'avec plateaux de protection',
   'Punnets' => 'barquettes', 'punnets' => 'barquettes',
   'Cartons' => 'cartons', 'cartons' => 'cartons', 'Carton' => 'carton',
   'Boxes' => 'boîtes', 'boxes' => 'boîtes',
   'Bags' => 'sacs', 'bags' => 'sacs', 'perforated bags' => 'sacs perforés',
   'Baskets' => 'paniers', 'Bins' => 'bacs', 'bins' => 'bacs',
   'Bulk bins' => 'bacs vrac', 'bulk bins' => 'bacs vrac',
   'Crates' => 'cagettes', 'crates' => 'cagettes', 'Crate' => 'cagette',
   'Lined cartons' => 'cartons doublés', 'lined cartons' => 'cartons doublés',
   'lined crates' => 'cagettes doublées', 'Lined' => 'doublés', 'lined' => 'doublés',
   'reusable crates' => 'cagettes réutilisables',
   'Trays' => 'plateaux', 'trays' => 'plateaux', 'Tray' => 'plateau', 'protective trays' => 'plateaux de protection',
   'Pouches' => 'sachets', 'pouches' => 'sachets',
   'Retail bags' => 'sacs détail', 'food-service bags' => 'sacs food-service',
   'Retail blocks' => 'blocs détail', 'Retail pouches' => 'sachets détail',
   'bulk cartons' => 'cartons vrac', 'lined bulk cartons' => 'cartons vrac doublés',
   'Retail cans' => 'boîtes détail', 'food-service cans' => 'boîtes food-service',
   'Drums' => 'fûts', 'Bulk' => 'vrac', 'bulk' => 'vrac', 'bulk formats' => 'formats vrac',
   'bulk containers' => 'contenants vrac', 'aseptic bulk' => 'vrac aseptique',
   'Single-layer' => 'simple couche', 'single-layer' => 'simple couche',
   'Layered cartons' => 'cartons en couches', 'layered cartons' => 'cartons en couches',
   'Cushioned cartons' => 'cartons amortis', 'Protected export cartons' => 'cartons export protégés',
   'protected export cartons' => 'cartons export protégés', 'protected cartons' => 'cartons protégés',
   'Shallow cartons' => 'cartons peu profonds', 'Shallow' => 'peu profonds', 'shallow' => 'peu profonds',
   'Ventilated banana cartons' => 'cartons banane ventilés',
   'Sleeved bunches' => 'bottes gainées', 'sleeved bunches' => 'bottes gainées',
   'Bunched' => 'en bottes', 'bunched' => 'en bottes', 'Bunches' => 'bottes', 'bunches' => 'bottes',
   'Braids' => 'tresses', 'Nets' => 'filets', 'nets' => 'filets',
   'secured pallet loads' => 'palettes sécurisées', 'pallet loads' => 'palettes',
   'Pallet' => 'palette', 'pallet' => 'palette',
   'Flow-wrapped trays' => 'plateaux flow-pack', 'Flow-wrapped' => 'flow-pack', 'flow-wrapped' => 'flow-pack',
   'Shrink-wrapped packs' => 'packs sous film', 'shrink-wrapped packs' => 'packs sous film',
   'Private-label retail' => 'détail MDD', 'Private-label' => 'MDD', 'private label subject to agreement' => 'marque de distributeur sous réserve d’accord',
   'food-service containers' => 'contenants food-service', 'food-service' => 'food-service', 'Food-service' => 'food-service',
   'Retail' => 'détail', 'retail' => 'détail',
   'Glass jars' => 'bocaux en verre', 'PET jars' => 'pots PET', 'jars' => 'bocaux',
   'Dark glass' => 'verre foncé', 'dark glass' => 'verre foncé', 'Glass' => 'verre', 'glass' => 'verre',
   'Cans' => 'boîtes métal', 'cans' => 'boîtes métal', 'Tins' => 'boîtes métal', 'tins' => 'boîtes métal',
   'plastic tubs' => 'godets plastiques', 'Plastic tubs' => 'godets plastiques', 'tubs' => 'godets',
   'Buckets' => 'seaux', 'buckets' => 'seaux', 'Bottles' => 'bouteilles', 'bottles' => 'bouteilles',
   'Containers' => 'contenants', 'containers' => 'contenants',
   'export cartons' => 'cartons export',
   'loose' => 'en vrac', 'Loose' => 'en vrac',
   ' or ' => ' ou ', ' with ' => ' avec ', ' in ' => ' en ', '; ' => ' ; ',
 ],
];

$spec_labels = [
 'varieties' => $L('Varieties / Types', 'الأصناف / الأنواع', 'Variétés / Types'),
 'handling'  => $L('Export Handling', 'التداول التصديري', 'Manipulation export'),
 'packing'   => $L('Packing', 'التعبئة', 'Emballage'),
 'chain'     => $L('Cold-Chain Guide', 'دليل السلسلة الباردة', 'Guide chaîne du froid'),
];
/* frozen/processed label overrides */
$spec_labels['forms'] = $L('Available Forms', 'الأشكال المتاحة', 'Formes disponibles');
$spec_labels['processing'] = $L('Processing & Handling', 'التصنيع والتداول', 'Transformation & manipulation');
$spec_labels['storage'] = $L('Frozen-Chain / Storage Guide', 'دليل السلسلة المجمدة / التخزين', 'Guide congélation / stockage');

$desc_templates = [
 'fresh-fruits' => [
   'ar' => static fn($n, $v, $p, $t) => "يُورَّد منتج $n ضمن برنامج نيل مابل للفواكه الطازجة بانتقاء دقيق للون والحجم والنضج وقوة العرض في الأسواق. الأصناف: $v. التعبئة: $p. $t",
   'fr' => static fn($n, $v, $p, $t) => "$n est fourni dans le programme fruits frais Nile-Maple, avec une sélection soignée de couleur, calibre, maturité et tenue en rayon. Variétés : $v. Emballage : $p. $t"],
 'fresh-vegetables' => [
   'ar' => static fn($n, $v, $p, $t) => "يُورَّد $n بجودة تصديرية منتظمة: شكل موحد وقشرة نظيفة وجودة طهي أو تصنيع معوّل عليها. الأصناف: $v. التعبئة: $p. $t",
   'fr' => static fn($n, $v, $p, $t) => "$n est fourni en qualité export constante : forme uniforme, peau propre et qualité culinaire ou industrielle fiable. Variétés : $v. Emballage : $p. $t"],
 'frozen-products' => [
   'ar' => static fn($n, $v, $p, $t) => "يُحفظ $n بنظام تجميد سريع IQF للحفاظ على اللون والقوام والنكهة على مدار العام. الأشكال: $v. التعبئة: $p. $t",
   'fr' => static fn($n, $v, $p, $t) => "$n est préservé par surgélation IQF pour garder couleur, texture et saveur toute l’année. Formes : $v. Emballage : $p. $t"],
 'processed-canned' => [
   'ar' => static fn($n, $v, $p, $t) => "يُجهّز $n وفق وصفات متفق عليها وبأوزان تعبئة مضبوطة ومعالجة حرارية وإغلاق محكم ومدة صلاحية موثقة. الأشكال: $v. التعبئة: $p. $t",
   'fr' => static fn($n, $v, $p, $t) => "$n est préparé selon recette convenue, poids net maîtrisé, traitement thermique, sertissage et DLUO documentée. Formes : $v. Emballage : $p. $t"],
];
$handling_templates = [
 'fresh-fruits' => [
   'ar' => 'تُقتطف الثمار عند النضج التجاري ويُزال حرار الحقل سريعًا، ثم تُغسل وتُدرج بالحجم واللون وتُعبأ بحماية مناسبة مع سلسلة تبريد نظيفة حتى الشحن.',
   'fr' => 'Les fruits sont récoltés à maturité commerciale, refroidis rapidement, lavés, calibrés par taille et couleur puis emballés avec protection et chaîne du froid propre jusqu’au chargement.'],
 'fresh-vegetables' => [
   'ar' => 'تُجهّز الحاصلات حسب المواصفة: معالجة ما بعد الحصاد، تنظيف أو غسيل، فرز وتدريج وفحص، ثم تبريد سريع مع رطوبة وتهوية مناسبتين لحماية المنتج في النقل.',
   'fr' => 'Les légumes sont préparés selon spécification : soins post-récolte, nettoyage ou lavage, tri, calibrage et contrôle, puis refroidissement rapide avec humidité et ventilation adaptées.'],
 'frozen-products' => [
   'ar' => 'تُغسل الخامات وتُقطع وتُدرج ثم تُجمد فرديًا بسرعة (IQF) وتُخزن عند −18 °م مع فصل الحبات وسلسلة تجميد غير منقطعة حتى الوجهة.',
   'fr' => 'Les matières sont lavées, coupées, calibrées puis surgelées individuellement (IQF) et stockées à −18 °C, grains séparés et chaîne du froid ininterrompue jusqu’à destination.'],
 'processed-canned' => [
   'ar' => 'تُفرز الخامات وتُغسل وتُجهز وفق الوصفة، ثم تُعبأ بالوزن الصافي المتفق عليه وتُعقم حراريًا وتُغلق بإحكام مع ضبط مدة الصلاحية ومتطلبات البطاقة.',
   'fr' => 'Les matières sont triées, lavées et préparées selon recette, puis remplies au poids net convenu, traitées thermiquement, serties, avec DLUO et étiquetage maîtrisés.'],
];
$chain_templates = [
 'ar' => static fn($a, $b) => $a !== null && $b !== null ? "عادة $a–$b °م" : ($a !== null ? "عادة $a °م" : 'حسب المواصفة'),
 'fr' => static fn($a, $b) => $a !== null && $b !== null ? "Généralement $a–$b °C" : ($a !== null ? "Généralement $a °C" : 'selon spécification'),
];

return compact('categories', 'product_names', 'packing_glossary', 'spec_labels', 'desc_templates', 'handling_templates', 'chain_templates')
    + require __DIR__ . '/seed_content2.php';
